Repository Azure/azure-sdk-tools, pull requests merged in 2020-05, with the labels that each got.

#487 Webhook router for EngSys
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter.Tests/Azure.Sdk.Tools.WebhookRouter.Tests.csproj
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter.Tests/UnitTest1.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/.gitignore
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Functions/RouteWebhookFunction.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/IRouter.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Payload.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/PayloadType.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/RouterException.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Rule.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Startup.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/host.json
  tools/webhook-router/WebhookRouter.sln
  tools/webhook-router/ci.yml
Labels: EngSys

#557 Check Enforcer override command
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
  tools/check-enforcer/README.md
Labels: EngSys

#564 Check Enforcer reliability pass
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/CheckEnforcerUnsupportedEventException.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookFunction.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
Labels: EngSys

#571 Webhook router payload validation
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Functions/RouteWebhookFunction.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Integrations/GitHub/GitHubWebhookSignatureValidator.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/AzureDevOpsRule.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/GenericRule.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/GitHubRule.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/IRouter.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Payload.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/PayloadType.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Rule.cs
Labels: EngSys

#576 Webhook Router optmization pass
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Startup.cs
Labels: EngSys

#575 Check Enforcer EventHubs cut-over
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverEventHubsFunction.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverHttpFunction.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubWebhookSignatureValidator.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Startup.cs
Labels: EngSys

#583 Standardize caching
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfigurationCacheEntry.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfigurationProvider.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubClientProvider.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Startup.cs
Labels: EngSys

#582 Ping functions for services
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverHttpFunction.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/PingFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/PingFunction.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Functions/PingFunction.cs
Labels: EngSys

#584 Check Enforcer back-off
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
Labels: EngSys

#591 Allow /check-enforcer override to handle duplicates.
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
Labels: EngSys

#581 [APIView] Java processor improvements
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/TokenKind.java
Labels: APIView

#563 Artifact Metadata Driven Docs Release
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/create-tags-and-git-release.ps1
  eng/common/scripts/git-branch-push.ps1
  eng/common/scripts/update-docs-metadata.ps1
  scripts/powershell/update-docrepo-from-source.ps1
Labels: EngSys

#593 Handle duplicate checks during reset command
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
Labels: EngSys

#596 Skip stale check-run events in Check Enforcer
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckRunHandler.cs
Labels: EngSys

#600 Correct boolean operator in CreateCheckAsync
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
Labels: EngSys

#604 Pipeline Witness scaffolding
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness.Tests/Azure.Sdk.Tools.PipelineWitness.Tests.csproj
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness.Tests/UnitTest1.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/.gitignore
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Azure.Sdk.Tools.PipelineWitness.csproj
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Functions/RunStateChangedFunction.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/host.json
  tools/pipeline-witness/PipelineWitness.sln
  tools/pipeline-witness/ci.yml
Labels: EngSys

#617 Emit value of WEBSITE_RESOURCE_GROUP in logs.
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/host.json
Labels: EngSys

#577 Add SubscriptionConfiguration support to TestResources
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
Labels: EngSys

#624 [Apiview] Handle custom exception types better in Java
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Labels: APIView

#634 trivial change to live-test-cleanup.yml
  eng/pipelines/live-test-cleanup.yml
Labels: EngSys

#637 Add condition to always run resource cleanup step
  eng/common/TestResources/remove-test-resources.yml
Labels: EngSys

#640 change for sourceless modules
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: EngSys

#655 Fix for pull request issue resetting pull requests.
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
Labels: EngSys

#658 Handle synchronize events in Check Enforcer
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
Labels: EngSys

#656 fix regression in AZC0004
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
Labels: API Analyzer
