Repository Azure/azure-sdk-tools, pull requests merged in 2020-08, with the labels that each got.

#835 Add PowerShell module install failure classifier.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/AzurePowerShellModuleInstallationFailureClassifier.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
Labels: EngSys

#838 Switch Android repo to pipeline generation on master
  eng/pipelines/pipeline-generation.yml
Labels: EngSys

#836 Detect Maven dependency download issues (broken pipes)
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/MavenBrokenPipeFailureClassifier.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
Labels: EngSys

#844 Fix android-pr repo sync.
  eng/pipelines/mirror-repos.yml
Labels: EngSys

#846 adding additional error codes
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys

#851 Fix for null reference exceptions in Pipeline Witness telemetry
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/MavenBrokenPipeFailureClassifier.cs
Labels: EngSys, Pipeline Witness

#860 Refactor GitHub Issues
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/CmdLineArgs.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Constants.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Email/EmailSender.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindCustomerReportedIssuesInInvalidStateFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindIssuesInBacklogMilestonesFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindIssuesInPastDueMilestonesFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindNewGitHubIssuesAndPrsAt2pmFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindNewGitHubIssuesAndPrsAt7amFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindPRsOlderThan3MonthsFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Helpers/GitHubHelpers.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Html/TableCreator.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Program.Debug.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Program.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseReport.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/ImpactArea.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/IssueType.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInBacklogMilestones.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInPastDueMilestones.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindNewGitHubIssuesAndPRs.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindStalePRs.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/ReportExecutionContext.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/ReportIssue.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Services/Configuration/ConfigurationService.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Services/Configuration/IConfigurationService.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Services/Configuration/RepositoryConfiguration.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Startup.cs
Labels: EngSys

#884 Updated Webhook Router dependencies.
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
Labels: EngSys, Webhook Router

#888 Update dependencies for GitHub Isssues.
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
Labels: EngSys, GitHub Issues

#887 Update dependencies for Pipeline Witness.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Azure.Sdk.Tools.PipelineWitness.csproj
Labels: EngSys

#885 Update Check Enforcer dependencies.
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
Labels: EngSys

#891 Fix null ref exception in Pipeline Witness.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/MavenBrokenPipeFailureClassifier.cs
Labels: EngSys, Pipeline Witness

#890 Improve logging for GitHub Issues.
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseReport.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Services/Configuration/ConfigurationService.cs
Labels: EngSys

#869 Tool to update ci.yml headers.
  scripts/powershell/Fix-YamlHeaders.ps1
  src/dotnet/Mgmt.CI.BuildTools/ci.yml
  tools/CreateRuleFabricBot/ci.yml
  tools/check-enforcer/ci.yml
  tools/github-issues/ci.yml
  tools/notification-configuration/ci.yml
  tools/pipeline-generator/ci.yml
  tools/pipeline-witness/ci.yml
  tools/version-guard/ci.yml
  tools/webhook-router/ci.yml
Labels: EngSys

#889 [APIView] Java improvements
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ConsiderFinalClassDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/FluentSetterReturnTypeDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
Labels: APIView

#870 Check links against the SHA commit
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys

#903 Fixed the log messages and log warning of the visited link.
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys

#857 Remove PackageId from C release
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys

#909 [APIView] Group API into packages with additional indentation
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Labels: APIView

#920 [APIView] Fix module-info module name display in Java APIView projects
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/RequiredBuilderMethodsDiagnosticRule.java
Labels: APIView

#921 [APIView] fix code ordering in Java APIViews
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Labels: APIView

#924 [APIView] fixes for Java tooling
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/ChildItem.java
Labels: APIView

#936 [Apiview] Java method sorting
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/MiscUtils.java
Labels: APIView
