Repository Azure/azure-sdk-tools, pull requests merged in 2020-11, with the labels that each got.

#1162 Add non-volatile state tracking to Check Enforcer
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/PullRequestTracker.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/PullRequestTrackingTicket.cs
Labels: Central-EngSys, Check Enforcer, EngSys

#1160 Update retry logic in Verify and Merge scipt, Update Delete-RemoteBra…
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/git-branch-push.ps1
  eng/pipelines/templates/steps/sync-directory.yml
  eng/scripts/Verify-And-Merge-PRs.ps1
Labels: auto-merge

#1167 Fix bug in git branch push
  eng/common/scripts/git-branch-push.ps1
  eng/pipelines/templates/steps/sync-directory.yml
Labels: auto-merge

#1175 Make sure we always log in as app or provisioner
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge

#1176 Fix to code-signing classifier.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/CodeSigningFailureClassifier.cs
Labels: Central-EngSys, EngSys, Pipeline Witness

#1163 Update subscription configuration schema to include new parameters
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: auto-merge

#1178 Refactor eng/common/README.md
  doc/README.md
  doc/common/common_engsys.md
  eng/common/README.md
Labels: auto-merge

#1188 Add debug flag to arm deployment command
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge

#1190 Remove invalid characters in basename sourced from username
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, auto-merge

#1170 Preprocess the markdowns contain deleted or renamed files.
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
Labels: auto-merge

#1199 Change live test resource DeleteAfterHours tag to 8 hours
  eng/common/TestResources/deploy-test-resources.yml
Labels: auto-merge

#1202 Add debugging link on resource deployment failures to log output
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge

#1153 Feature/change log tools improvement
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: auto-merge

#1195 Change domain for FabricBot
  tools/CreateRuleFabricBot/CreateRuleFabricBot/Service/RequestSender.cs
Labels: Central-EngSys, EngSys

#1210 Restore initial AzContext for New-TestResources
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: auto-merge

#1204 Add auth header checks to DevOps rule.
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter.Administration/New-AzureDevOpsRuleCredentials.ps1
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Functions/RouteWebhookFunction.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/AzureDevOpsRule.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/RouterAuthorizationException.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Startup.cs
Labels: Central-EngSys, Check Enforcer, EngSys

#1203 Refactoring common shared tools
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/create-tags-and-git-release.ps1
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: auto-merge

#1171 [APIView] Java improvements to APIView
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/DiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ConsiderFinalClassDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/FluentSetterReturnTypeDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/IllegalMethodNamesDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/IllegalPackageAPIExportsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ImportsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingAnnotationsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavaDocDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/NoPublicFieldsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/PackageNameDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/RequiredBuilderMethodsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/UpperCaseNamingDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
Labels: APIView

#1222 Switch back to smoke-test before doc publishing error gets fixed.
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys, auto-merge

#1219 Move entire docgeneration into common tools
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/assets/logo.svg
  eng/common/docgeneration/docfx.json
  eng/common/docgeneration/templates/matthews/partials/affix.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.header.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/enum.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/namespace.tmpl.partial
  eng/common/docgeneration/templates/matthews/styles/main.css
  eng/common/docgeneration/templates/matthews/styles/main.js
  eng/common/pipelines/templates/steps/docindex.yml
Labels: auto-merge

#1226 Fixed the docindex.yml and rename the functions
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/docindex.yml
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys, auto-merge

#1229 Fixed the bug of the wrong parameter
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys, auto-merge
