Repository Azure/azure-sdk-tools, pull requests merged in 2020-12, with the labels that each got.

#1026 Add "weekly" convention to pipeline generator
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
Labels: Central-EngSys

#1235 Webhook Router: Payload output on routing errors
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/RouteConfigurationException.cs
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
Labels: Central-EngSys, EngSys, Webhook Router

#1233 Support moniker specific folders for readmes (and incoming service overviews)
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: auto-merge

#1244 Classifier for Azurite install failures.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/AzuriteInstallFailureClassifier.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
Labels: Central-EngSys, EngSys, Pipeline Witness

#1230 [APIView] Misc Java-specific improvements
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/NoLocalesInJavadocUrlDiagnosticRule.java
Labels: APIView

#1257 Make up the css using for .net sdk github io pages
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/templates/matthews/styles/main.css
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: auto-merge

#1243 Invoke template live test pipeline during eng common sync
  eng/common/scripts/modules/ChangeLog-Operations.psm1
  eng/common/scripts/modules/Package-Properties.psm1
  eng/common/scripts/modules/common-manifest.psd1
  eng/pipelines/templates/steps/sync-directory.yml
Labels: auto-merge

#1266 Create PR to target against master
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: auto-merge

#1271 Filter PRs from search for invalid customer issues.
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
Labels: Central-EngSys, EngSys, GitHub Issues

#1270 Resolve git longpath error when applying documentation updates
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: auto-merge

#1274 Added a step of skipping package json update for spring boot packages
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys, auto-merge

#1273 Support alpha and azure pipeline build version formats for SemVer parsing and sorting
  eng/common/scripts/SemVer.ps1
Labels: auto-merge

#1285 Fixed the bug of replacing img src with href text
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: auto-merge

#1287 Move common code into eng common in tools
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge
