Repository Azure/azure-sdk-tools, pull requests merged in 2020-07, with the labels that each got.

#742 Correct typo and broader applicability.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/DownloadSecretsFailureClassifier.cs
Labels: EngSys, Pipeline Witness

#748 Remove param validation from create-tags-and-git-release.ps1 that breaks C release
  eng/common/scripts/create-tags-and-git-release.ps1
Labels: EngSys

#745 Log webhook payloads
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
Labels: EngSys, Webhook Router

#738 Setup mirroring for Android and iOS mirrors.
  eng/pipelines/mirror-repos.yml
Labels: EngSys

#751 [Java-BugFix] Fixes a few bugs, skipping double quote character, display annotation on field, unique id in interface annotaion, etc
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
Labels: API Analyzer, bug, java

#761 turn off recursion
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: EngSys

#787 Quick fix to typo in test provisioner.
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys

#788 Treat any import error during stubgen as hard error
  packages/python-packages/api-stub-generator/apistub/_stub_generator.py
Labels: EngSys

#799 AZC0011: Handle benchmarking assemblies
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0011Tests.cs
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyAttributesAnalyzer.cs
Labels: API Analyzer

#783 Updates to release C++
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/create-tags-and-git-release.ps1
Labels: EngSys

#802 Remove iOS from pipeline generation.
  eng/pipelines/pipeline-generation.yml
Labels: EngSys

#808 Always clean up resources (runs during cancel)
  eng/common/TestResources/remove-test-resources.yml
Labels: EngSys

#809 Add cosmos emulator install/start.
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
Labels: EngSys

#822 [Test Resources] Add Environment Variables
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, enhancement

#819 Add retry logic for rate limiting exceptions.
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseFunction.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInBacklogMilestones.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInPastDueMilestones.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindNewGitHubIssuesAndPRs.cs
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindStalePRs.cs
Labels: EngSys

#828 [Test Resources] Extend with Storage Endpoint
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, enhancement
