Repository Azure/azure-sdk-tools, pull requests merged in 2021-01, with the labels that each got.

#1296 Creation of tools - git-tasks pipeline
  eng/common/scripts/Delete-RemoteTag.ps1
  eng/pipelines/git-tasks.yml
Labels: Central-EngSys, EngSys

#1299 Updates to Update-Changelog.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: auto-merge

#1293 Add resource provisioning variables to UP pipelines and improve readability
  eng/pipelines/pipeline-generation.yml
Labels: Central-EngSys

#1278 Add Devops Release Item scripts
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: auto-merge

#1298 Update latest folder with one index.html includes the redirect links
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: auto-merge

#1302 Make the user agent configurable for link checker scripts
  eng/common/scripts/Verify-Links.ps1
Labels: auto-merge

#1301 Remove old Update-Change-Log.ps1
  eng/common/Update-Change-Log.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: auto-merge

#1306 Allow configuration of a suffix for each config item
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: auto-merge

#1308 Revert "Remove old Update-Change-Log.ps1"
  eng/common/Update-Change-Log.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: auto-merge

#1304 Fix condition for test generation in prepare-pipelines
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: auto-merge

#1314 Update pipeline generation tool to support test variant pipelines
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: auto-merge

#1322 Use tools environment and disable CG.
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
Labels: Central-EngSys, EngSys

#1318 Update error message in tools repo
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/update-docs-ci.ps1
Labels: auto-merge

#1327 Ensure bypass conditional template gets run for 1es ubuntu image
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: auto-merge

#1317 Docs Gen Pulls Tools from Tag
  eng/common/pipelines/templates/steps/get-pr-owners.yml
Labels: auto-merge

#1251 Pre release prep
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge

#1335 Update Changelog Logic to accommodate older entries
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: auto-merge

#1343 Fixed the problem of no display name issue
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/docfx.json
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: auto-merge

#1341 Run the link verification step even previous step failed.
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: auto-merge

#1346 Add provisoiner secrets to C++ pipelines that run live tests
  eng/pipelines/pipeline-generation.yml
Labels: Central-EngSys

#1345 Enforce API approval status for GA and include SDK type in package pr…
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: auto-merge
