Repository Azure/azure-sdk-tools, pull requests merged in 2021-03, with the labels that each got.

#1450 Auto update all reviews in the background after parser is updated
  src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: Central-EngSys

#1457 AZC0011 allows Perf assemblies
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0011Tests.cs
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyAttributesAnalyzer.cs
Labels: API Analyzer

#1455 Fix issue that prevents apiview automatic workflow for Java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Labels: APIView

#1456 Fix language short typo
  eng/common/scripts/common.ps1
Labels: auto-merge

#1459 Move SetTestPipelineVersion.ps1 to eng/common
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: auto-merge

#1467 Fix PackageName typo
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: auto-merge

#1465 Enable APIView status check
  eng/common/pipelines/templates/steps/create-apireview.yml
Labels: auto-merge

#1448 Added more logging to API view create
  eng/common/scripts/Create-APIReview.ps1
Labels: auto-merge

#1461 Fix bug where imported matrix parameter duplicates are not overrided
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: Central-EngSys, auto-merge

#1470 Fix logic in SetTestPipelineVersionInEngCommon
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: auto-merge

#1472 Move SetTestPipeline into its own template
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Labels: auto-merge

#1410 Add CI trigger back to pipeline generator
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
Labels: Central-EngSys, EngSys

#1452 Use sparse checkout for generate matrix job
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
Labels: Central-EngSys, auto-merge

#1475 Use latest pipeline generator
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys, Pipeline Generator, auto-merge

#1479 Sort changelogs by date then version
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/SemVer.ps1
Labels: auto-merge

#1418 Update Package Properties Logic
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: auto-merge

#1496 Revert to Checking only ci.yml
  eng/common/scripts/Package-Properties.ps1
Labels: auto-merge

#1463 Add replace operation to matrix config
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: Central-EngSys, auto-merge

#1498 [matrix] Fix null check against matrix parameter array
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: Central-EngSys, auto-merge

#1489 Add ability to open PR as draft to Submit-PullRequest.ps1
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Submit-PullRequest.ps1
Labels: auto-merge

#1502 Add ReleaseVersionSemVer to ensure version can be sorted
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: auto-merge

#1491 [Java API view] Show all annotations by default
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Labels: APIView, java

#1476 Add ReleaseTrackingOnly option to Prepare-Release
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: auto-merge

#1514 [matrix] Handle null values when generating display names
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: auto-merge

#1517 Add ChangelogPath to Update-ChangeLog.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: auto-merge

#1478 Actually pass the _content_ of the reviewers or teamreviewers variable to the Submit-Pullrequest.ps1 script
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: auto-merge

#1508 Skip API create step when running from feature branch with non GA version
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Create-APIReview.ps1
Labels: auto-merge

#1521 [matrix] Fix issue where 2d index arrays with length 1 get flattened by powershell
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: Central-EngSys, auto-merge

#1477 Checked in code to some branch directly
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/git-push-changes.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/git-branch-push.ps1
Labels: auto-merge

#1527 Add DependsOn parameter to matrix job generation template
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, auto-merge

#1520 Automatic review should only have one revision in review pending state
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: APIView, Central-EngSys
