Repository Azure/azure-sdk-tools, pull requests merged in 2021-02, with the labels that each got.

#1351 tweaks to New-TestResources readme
  eng/common/TestResources/README.md
Labels: auto-merge

#1361 Fix DateTime bug
  eng/common/scripts/Prepare-Release.ps1
Labels: auto-merge

#1359 Pool provisioning config
  config/1es-pools/azsdk-pool-mms-ubuntu-1604-general/provisioning.json
  config/1es-pools/azsdk-pool-mms-ubuntu-1804-general/provisioning.json
  config/1es-pools/azsdk-pool-mms-ubuntu-2004-general/provisioning.json
  config/1es-pools/azsdk-pool-mms-win-2019-general/provisioning.json
Labels: Central-EngSys, EngSys

#1353 Use a helper function to normalize the package name for readme
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: auto-merge

#1364 Support sub directory for artifact location
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: auto-merge

#1365 Updated cosmos emulator yml script
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
Labels: auto-merge

#1369 Include all classes in namespace and skip only Details namespace
  src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
Labels: Central-EngSys

#1366 Scan all duplicate artifacts which set hide to true
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: auto-merge

#1376 Update devops helper script based on changes in azure-sdk repo
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/SemVer.ps1
Labels: auto-merge

#1393 Hide the package which set to true instead of putting to Other page
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: auto-merge

#1303 Add changelog collection
  eng/common/scripts/Collect-ChangeLogs.ps1
Labels: auto-merge

#1358 Add eng/common break check
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: auto-merge

#1386 Enable passing devops pat for work item scripts
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: auto-merge

#1307 Change script parameters to Boolean
  eng/common/scripts/Update-ChangeLog.ps1
Labels: auto-merge

#1401 Update eng-common-workflow-enforcer
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: auto-merge

#1405 Allow logging into specific subscription
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: auto-merge

#1408 Improve TestResources docs and logging
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/README.md
Labels: auto-merge

#1371 Rework verify agent OS step.
  eng/common/pipelines/templates/steps/verify-agent-os.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: Central-EngSys, EngSys, auto-merge

#1406 [APIView] add support for displaying important maven details
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/IllegalPackageAPIExportsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/ChildItem.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Dependency.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Gav.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/MavenGAV.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Pom.java
Labels: APIView, java

#1374 Create package property file using artifact name
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: auto-merge

#1412 [APIView] Java - don't create multiple 'compile scope' sections
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Dependency.java
Labels: APIView

#1417 Fix for NPE in APIView for Java libraries that lack maven pom information
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
Labels: APIView

#1419 Apiview maven simplifications
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Labels: APIView

#1396 Change other version to all versions
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: auto-merge

#1422 Disable NuGet sec analysis error.
  eng/pipelines/pipeline-generation-single.yml
  eng/pipelines/pipeline-generation.yml
Labels: Central-EngSys, EngSys

#1415 Only run eng/common check when target branch is master
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: auto-merge

#1425 Trim off the target branch
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
Labels: auto-merge

#1429 Add job matrix generation scripts
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/samples/matrix-job-sample.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: Central-EngSys, auto-merge

#1436 Update pipeline generator version to include weekly convention name fix
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, auto-merge

#1428 Restore pipeline output variable for Agent OS name
  eng/common/pipelines/templates/steps/verify-agent-os.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: Central-EngSys

#1421 Add spell check tools to eng/common
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: Central-EngSys, auto-merge

#1447 Update Prepare-Release script
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/logging.ps1
Labels: auto-merge
