Repository Azure/azure-sdk-tools, pull requests merged in 2021-11, with the labels that each got.

#2184 Add ci/publish and readme for stress test generator
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/cluster/kubernetes/generator/README.md
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Program.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Stress.Generator.csproj
  tools/stress-cluster/cluster/kubernetes/generator/ci.yml
Labels: Central-EngSys, pillar-reliability, Stress

#2177 Create an issue template
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: auto-merge

#2203 Use https for sparse checkout command
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: auto-merge, Central-EngSys

#2179 Login and Pull docker image.
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: auto-merge

#2188 [Test-Proxy] More explicit error handling around `Admin/Add<Sanitizer/Matcher/Transform>`
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminFunctionalityTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/UriRegexSanitizer.cs
Labels: Central-EngSys

#2198 Automate stress test eng-common-tools dockerfile release pipeline
  eng/containers/ci.yml
Labels: Central-EngSys

#2053 Changing inline bash for stress test resource deployment to new-testresources.ps1
  eng/common/TestResources/New-TestResources.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/.gitignore
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/Dockerfile
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/prepare.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/test-resources-post.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
Labels: auto-merge, Central-EngSys

#2199 Stress test usability updates
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/pipelines/stress-test-release.yml
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/chaos/examples/network-stress-example/templates/testjob.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/parameters.json
  tools/stress-cluster/cluster/kubernetes/generator/README.md
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator.Tests/GeneratorTest.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Program.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Chaos/NetworkChaos.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Job.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/StressTestPackage.cs
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_deploy_configmap.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_deploy_volumes.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
Labels: auto-merge, Central-EngSys, pillar-reliability, Stress

#2218 Don't Match Snippet Boundaries that are Missing an ID
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
Labels: Java

#2202 Add prompt before replacing latest release title on prepare release run
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: auto-merge

#2207 [OAV] Converter Prototype
  .gitignore
  tools/oav-traffic-converter/LICENSE
  tools/oav-traffic-converter/README.md
  tools/oav-traffic-converter/ci.yml
  tools/oav-traffic-converter/input-example/input-example.json
  tools/oav-traffic-converter/input-example/test_retry.pyTestStorageRetrytest_retry_on_server_error.json
  tools/oav-traffic-converter/output-example/output-example.json
  tools/oav-traffic-converter/output-example/test_retry.pyTestStorageRetrytest_retry_on_server_error0.json
  tools/oav-traffic-converter/package.json
  tools/oav-traffic-converter/src/cli.ts
  tools/oav-traffic-converter/tsconfig.json
Labels: Central-EngSys

#2222 Fix stress static secret provisioning missing trailing newline and windows support
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
  tools/stress-cluster/cluster/azure/main.bicep
  tools/stress-cluster/cluster/azure/monitoring/workbook.bicep
  tools/stress-cluster/cluster/azure/parameters/dev.json
  tools/stress-cluster/cluster/azure/parameters/prod.json
  tools/stress-cluster/cluster/azure/parameters/test.json
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys, pillar-reliability, Stress

#2219 Adding conditional docker restart
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-docker.yml
Labels: auto-merge

#2223 Updating helm chart for stress-test-addons
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  tools/stress-cluster/chaos/examples/.gitignore
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/cluster/README.md
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.sh
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
Labels: auto-merge, Central-EngSys, pillar-reliability, Stress

#2208 [APIView Python] Eliminate duplicate kwargs
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/_version.py
  packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
  packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
Labels: APIView

#2211 [APIView Python] Fix truncated return types
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
Labels: APIView

#2209 [APIView Python] Fix logic for determining if methods are async
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
Labels: APIView

#2240 Re-add get-codeowners.ps1
  eng/common/scripts/get-codeowners.ps1
Labels: auto-merge

#2241 Use namespaced cluster role and binding for stress watcher
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
Labels: Central-EngSys, Stress

#2242 Resolve mac agent failure
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge, Central-EngSys

#2246 update python parser version and update older review files
  src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: Central-EngSys

#2249 Additional Tool Fixes
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge, Central-EngSys

#2251 General codesnippet-maven-plugin Changes
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/SnippetBaseMojo.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/UpdateCodesnippet.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/VerifyCodesnippet.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetError.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetLengthError.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetMismatchError.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetMissingError.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetOperationResult.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/VerifyResult.java
  packages/java-packages/codesnippet-maven-plugin/src/test/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacerTests.java
Labels: Java

#2247 Use arm template parameters as sole input for live test environment variables
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/clouds/AzureChinaCloud.json
  eng/common/TestResources/clouds/AzureCloud.json
  eng/common/TestResources/clouds/AzureUSGovernment.json
Labels: auto-merge, Central-EngSys

#2140 Clean up resource group deployments on stress test completion
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
  tools/stress-cluster/services/Stress.Watcher/publish.ps1
  tools/stress-cluster/services/Stress.Watcher/src/PodEventHandler.cs
  tools/stress-cluster/services/Stress.Watcher/src/Program.cs
  tools/stress-cluster/services/Stress.Watcher/src/Stress.Watcher.csproj
  tools/stress-cluster/services/Stress.Watcher/tests/PodEventHandlerTest.cs
Labels: Central-EngSys

#2259 Adding Redirection of nohup-ed tool runs so we can dump the log later
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge

#2274 updating container ci trigger
  eng/containers/ci.yml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
Labels: Central-EngSys

#2283 update stress test addon chart.yaml for PR #2140
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
Labels: Central-EngSys

#2276 Prefix matrix generation service directory sparse checkout with 'sdk'
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: auto-merge, Central-EngSys

#2267 fix bug in prepare relaease
  eng/common/scripts/Prepare-Release.ps1
Labels: auto-merge

#2272 Make sure clean-up scripts return collections
  eng/common/scripts/Helpers/Resource-Helpers.ps1
  eng/scripts/live-test-resource-cleanup.ps1
Labels: auto-merge

#2266 Add cluster provisioner secrets and documentation for stress watcher deployment.
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/README.md
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher-cluster-role-binding.yaml
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher-cluster-role.yaml
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_debug_file_volumes.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_env_volumes.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_env.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-cluster-secret-provider.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-file-share-secret-provider.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys

#2290 [Test-Proxy] Fix default startup location in `docker-start-proxy.ps1`, Update `windows` tool initialize
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge, Central-EngSys

#2292 [Test-Proxy] Exclude `content-length` from BodilessMatcher matching
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/BodilessMatcher.cs
Labels: Central-EngSys

#2293 [Test-Proxy] `/Playback/Start/` should always populate a json response body
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Labels: Central-EngSys

#2301 Reduce review update delay
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: Central-EngSys

#2230 Minor APIView improvements for Java
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavaDocDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
Labels: APIView, Java

#2317 [Test-Proxy] Header Exclusion Updates
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Azure.Sdk.Tools.TestProxy.Tests.csproj
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/if_none_match_present.json
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/HeaderlessMatcher.cs
Labels: Central-EngSys

#2321 [Test-Proxy] Bump tool and docker versions
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge, Central-EngSys

#2306 Declare transitive dependency on Az.KeyVault 3.4.1
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: auto-merge

#2320 [Test-Proxy] Set Explicit Header on TestRecorderMismatchException
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
Labels: Central-EngSys

#2322 Install and Run code owner tools in get-codeowner.ps1
  eng/common/scripts/get-codeowners.ps1
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CODEOWNERS
  tools/code-owners-parser/ci.yml
Labels: auto-merge

#2333 [Test-Proxy] Change storage directory from `/etc/testproxy` -> `/srv/testproxy`
  eng/common/testproxy/docker-start-proxy.ps1
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
  tools/test-proxy/docker/README.md
  tools/test-proxy/docker/dockerfile
  tools/test-proxy/docker/dockerfile-win
  tools/test-proxy/startup-scripts/start-server.js
  tools/test-proxy/startup-scripts/start-server.ps1
  tools/test-proxy/startup-scripts/start-server.py
Labels: auto-merge, Central-EngSys

#2086 Take in the doc author from pipeline
  eng/common/pipelines/templates/steps/get-pr-owners.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/get-codeowners.ps1
  tools/code-owners-parser/ci.yml
Labels: auto-merge

#2258 Prepare codesnippet-maven-plugin for Release
  packages/java-packages/codesnippet-maven-plugin/pom.xml
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/Codesnippet.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/VerifyResult.java
  packages/java-packages/codesnippet-maven-plugin/src/test/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacerTests.java
Labels: Java

#2337 [stress] Clarify the adhoc instructions a bit more.
  tools/stress-cluster/chaos/README.md
Labels: auto-merge

#2348 Run install command under tool path
  eng/common/scripts/get-codeowners.ps1
Labels: auto-merge

#2335 [Test-Proxy] Adding some additional error handling, updating all explicit exceptions to surface with coherent errors
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Labels: Central-EngSys

#2331 Stress test pipeline auto-discover stress test
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  eng/pipelines/stress-test-release.yml
Labels: auto-merge, Central-EngSys
