Repository Azure/azure-sdk-tools, pull requests merged in 2021-08, with the labels that each got.

#1863 Swift filter button and create review help text for swift reviews
  src/dotnet/APIView/APIViewWeb/Languages/SwiftLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
  src/dotnet/APIView/APIViewWeb/Startup.cs
Labels: APIView, Central-EngSys

#1869 Initial support for parsing and displaying XML files in APIView
  src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
  src/dotnet/APIView/APIViewWeb/Startup.cs
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/Analyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/XMLASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ModuleInfoDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/ChildItem.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Gav.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Pom.java
Labels: APIView

#1852 Add ability to leave SourceBranch empty when queueing a build
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Queue-Pipeline.ps1
Labels: auto-merge, Central-EngSys

#1883 Windows Docker container should dump files in the same folder within the container as Linux container
  tools/test-proxy/docker/dockerfile-win
Labels: auto-merge

#1885 [GitHub Labels] Diff-vs-Common
  tools/github-labels/README.md
  tools/github-labels/deploy-labels.ps1
  tools/github-labels/diff-repo-labels.ps1
  tools/github-labels/refresh-snapshots.ps1
  tools/github-labels/repository-snapshots/autorest.csv
  tools/github-labels/repository-snapshots/autorest.go.csv
  tools/github-labels/repository-snapshots/autorest.java.csv
  tools/github-labels/repository-snapshots/autorest.python.csv
  tools/github-labels/repository-snapshots/autorest.swift.csv
  tools/github-labels/repository-snapshots/autorest.typescript.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-c.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-cpp.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-go-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-go.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-java-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-java.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-js.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-net-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-net.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-python-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-python.csv
  tools/github-labels/repository-snapshots/perks.csv
  tools/github-labels/scan-new-labels.ps1
Labels: GitHub Issues

#1866 Update stress test template to handle Scenario name and group deployments
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/parameters.json
  tools/stress-cluster/chaos/examples/stress-deployment-example/test-resources.bicep
  tools/stress-cluster/chaos/examples/stress-deployment-example/test-resources.json
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.sh
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_container_env.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_env_volumes.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_env.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
Labels: auto-merge, Central-EngSys

#1899 [stress testing] Use UTC 'Z' zone designator to work with powershell DateTime parsing
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.sh
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
Labels: Central-EngSys

#1894 Purge Key Vaults after deleting resource group
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/scripts/Helpers/Resource-Helpers.ps1
  eng/scripts/live-test-resource-cleanup.ps1
Labels: auto-merge

#1876 Fix New-TestResources.ps1 to run pre/post deployment script
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge

#1884 Add Rest Method checks to Prepare-Release
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: auto-merge

#1902 Fix resource clean-up script
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/scripts/Helpers/Resource-Helpers.ps1
  eng/scripts/live-test-resource-cleanup.ps1
Labels: auto-merge

#1887 Spell Check: Add support for 'files' configuration and failing pipeline
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: auto-merge

#1911 [stress testing] Prevent secret logging from resource group deployment results
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
Labels: Central-EngSys

#1901 Discovery/script path fixes for stress test release pipeline
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/pipelines/stress-test-release.yml
Labels: auto-merge, Central-EngSys

#1909 [Test-Proxy] eng/common templates
  .gitignore
  eng/common/scripts/common.ps1
  eng/common/scripts/trust-proxy-certificate.ps1
  eng/common/testproxy/apply-dev-cert.sh
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/dotnet-devcert.crt
  eng/common/testproxy/dotnet-devcert.pfx
  eng/common/testproxy/localhost.conf
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
  eng/containers/ci.yml
  tools/http-fault-injector/README.md
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
  tools/test-proxy/docker/README.md
  tools/test-proxy/docker/dev_certificate/.gitattributes
  tools/test-proxy/docker/dockerfile
  tools/test-proxy/docker/dockerfile-win
  tools/test-proxy/docker/prepare.ps1
  tools/test-proxy/documentation/trusting-cert-per-language.md
  tools/test-proxy/documentation/using-in-devops.md
Labels: Central-EngSys

#1913 Enable API review approval check for Java spring packages
  eng/common/scripts/Create-APIReview.ps1
Labels: auto-merge, Central-EngSys

#1875 APIview misc fixes
  src/dotnet/APIView/APIViewWeb/Client/css/site.scss
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
  src/dotnet/APIView/APIViewWeb/TagHelpers/ActiveIfTagHelper.cs
Labels: Central-EngSys

#1919 Removing FilterPoliCheckResults.ps1
  eng/common/scripts/FilterPoliCheckResults.ps1
Labels: auto-merge

#1920 [Test-Proxy] Allow Version Flag. Output Json files explicitly.
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
Labels: Central-EngSys

#1912 Attempt to purge all vaults, managed HSMs
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/scripts/Helpers/Resource-Helpers.ps1
  eng/pipelines/live-test-cleanup.yml
  eng/scripts/live-test-resource-cleanup.ps1
Labels: auto-merge

#1924 Fix query batch processing
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: auto-merge

#1926 Remove old unused update changelog script
  eng/common/Update-Change-Log.ps1
Labels: auto-merge

#1929 Swift parser should not process uploaded json file
  src/dotnet/APIView/APIViewWeb/Languages/SwiftLanguageService.cs
Labels: Central-EngSys

#1930 Swift APIView: add support for Objective-C and Mixed Source frameworks
  src/swift/README.md
  src/swift/Sources/APIViewManager.swift
  src/swift/Sources/CommandLineArguments.swift
  src/swift/Sources/Models/TokenFile.swift
  src/swift/Sources/Models/TypeModel.swift
  src/swift/Sources/Util/Errors.swift
  src/swift/SwiftAPIView.xcodeproj/project.pbxproj
  src/swift/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
Labels: APIView

#1918 [stress testing] Update docs, resiliency for deploy script
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  tools/stress-cluster/chaos/README.md
Labels: auto-merge, Central-EngSys

#1943 Bug fix: Storing .env file for bicep file at service dir
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge

#1952 Skip eng common workflow enforcer for private repos
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: auto-merge

#1953 Add unique id to default base name
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge
