Repository Azure/azure-sdk-tools, pull requests merged in 2021-10, with the labels that each got.

#2059 Existing pull request model is not fetched correctly
  src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
Labels: Central-EngSys

#2060 Update docker-start-proxy.ps1
  eng/common/testproxy/docker-start-proxy.ps1
Labels: auto-merge

#2067 Fix Missing README Code Fence Bug
  packages/java-packages/codesnippet-maven-plugin/pom.xml
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
  packages/java-packages/codesnippet-maven-plugin/src/test/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacerTests.java
  packages/java-packages/codesnippet-maven-plugin/src/test/resources/project-to-test/readme_code_fence_no_snippet_after.txt
  packages/java-packages/codesnippet-maven-plugin/src/test/resources/project-to-test/readme_code_fence_no_snippet_before.txt
Labels: Java

#2071 Revert change back
  eng/common/testproxy/docker-start-proxy.ps1
Labels: auto-merge

#2072 Add stress test generator CLI
  tools/stress-cluster/chaos/examples/network-stress-example/templates/network_loss.yaml
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator.Tests/GeneratorTest.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator.Tests/ResourceTest.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator.Tests/Stress.Generator.Tests.csproj
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Generator.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Program.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Prompter.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/ResourceProperty.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/ResourcePropertyInfo.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Chaos/NetworkChaos.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Job.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Resource.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/StressTestPackage.cs
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Stress.Generator.csproj
  tools/stress-cluster/cluster/kubernetes/generator/generator.sln
Labels: Central-EngSys, pillar-reliability, Stress

#2095 Mitigate relative path calculation error on multiple iterations
  eng/common/scripts/Save-Package-Properties.ps1
Labels: auto-merge

#2127 Update list of cosmos containers to backup
  scripts/python/apiview-syncdb/sync_cosmosdb.py
Labels: Central-EngSys
