Repository Azure/azure-sdk-tools, pull requests merged in 2021-05, with the labels that each got.

#1579 Allow propogation of SetDevVersion.
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys, auto-merge

#1524 Make RELEASE_TITLE_REGEX more specific
  doc/common/common_engsys.md
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: auto-merge

#1590 Chunk ordering error classifier.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/CacheChunkOrderingFailureClassifier.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
Labels: Central-EngSys, EngSys

#1589 Add more partner subscriptions to live test cleanup pipeline
  eng/pipelines/live-test-cleanup.yml
  tools/live-test-cleanup/cleanup.ps1
Labels: Central-EngSys

#1596 Revert changes to SetDevVersion.
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys, auto-merge

#1597 Add better error handling in Prepare-Release
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: auto-merge

#1594 Use sparse checkout for eng/common sync PRs
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/pipelines/eng-common-sync.yml
  eng/pipelines/templates/steps/sync-directory.yml
Labels: auto-merge

#1602 Enable iOS pipeline generation.
  eng/pipelines/pipeline-generation.yml
Labels: Central-EngSys, EngSys

#1598 Allow Multiple Invocations of `archetype-sdk-tests-generate` within the same stage
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: auto-merge

#1585 Sparse checkout docs repository in release step
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/pipelines/templates/steps/sync-repo-branch.yml
Labels: Central-EngSys, auto-merge

#1615 Move docindex.yml from steps -> jobs
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: auto-merge

#1627 Refactor sparse checkout template: idempotency and no yaml loops
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: auto-merge

#1629 Add Get-ChangeLogEntriesFromContent
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: auto-merge

#1635 Update common engineering system for docs onboarding
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge

#1606 Enable Caching of PS Modules
  eng/common/TestResources/AzurePowerShellV4/Utility.ps1
  eng/common/TestResources/Import-AzModules.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
  eng/common/TestResources/setup-environments.yml
  eng/common/pipelines/templates/steps/cache-ps-modules.yml
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
  eng/pipelines/live-test-cleanup.yml
  eng/scripts/live-test-resource-cleanup.ps1
  tools/live-test-cleanup/README.md
Labels: auto-merge
