Repository Azure/azure-sdk-tools, pull requests merged in 2021-06, with the labels that each got.

#1611 Add a step in prepare release to check API review status for GA version
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: Central-EngSys, auto-merge

#1658 Add the ability to check for open pull request to a different repo.
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: auto-merge

#1645 Check remote refs instead of local refs when applying/pushing changes
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, auto-merge

#1654 Use generate matrix job name parameter as display name
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, auto-merge

#1633 Update format of new Changelog Entry
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: auto-merge

#1685 Strict mode needs the variables initialized
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: auto-merge

#1689 Adding Informational Views
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/InfoTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordedTestSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Info.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/ActionDescription.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/ActiveMetadataModel.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/AvailableMetadataModel.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/RunTimeMetadataModel.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/ContinuationSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/HeaderKeyValueSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/OAuthResponseSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/ReplaceRequestSubscriptionId.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/UriRegexSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Transforms/ApiVersionTransform.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Transforms/ClientIdTransform.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Transforms/StorageRequestIdTransform.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/ActiveExtensions.cshtml
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/MetadataDump.cshtml
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/css.cshtml
Labels: Central-EngSys

#1688 Add verification of changelog sections
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: auto-merge

#1711 Fix hard-coded master
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/update-docs-metadata.ps1
Labels: auto-merge

#1716 Update links with master to use main
  .azure-pipelines/apiview.yml
  .azure-pipelines/dotnet.yml
  .azure-pipelines/warden.yml
  doc/README.md
  eng/common/README.md
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/pipelines/eng-common-sync.yml
  eng/pipelines/githubio-linkcheck.yml
  eng/pipelines/pipeline-generation-single.yml
  eng/pipelines/setup-tutorial-branch.yml
  eng/pipelines/templates/steps/sync-directory.yml
  eng/pipelines/templates/steps/sync-repo-branch.yml
  packages/python-packages/doc-warden/README.md
  src/dotnet/Mgmt.CI.BuildTools/ci.yml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
  tools/CreateRuleFabricBot/ci.yml
  tools/check-enforcer/ci.yml
  tools/github-issues/ci.yml
  tools/http-fault-injector/README.md
  tools/http-fault-injector/ci.yml
  tools/notification-configuration/ci.yml
  tools/notification-configuration/github-codeowner-subscriber/CodeOwnersParser.cs
  tools/pipeline-generator/ci.yml
  tools/pipeline-witness/ci.yml
  tools/version-guard/ci.yml
  tools/webhook-router/ci.yml
Labels: auto-merge

#1719 Update pipeline generation tool version
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/pipelines/pipeline-generation.yml
Labels: auto-merge

#1678 Auto API review should only have one pending review since last approval
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: Central-EngSys

#1704 Add stress cluster bicep files and buildout readme
  tools/stress-cluster/cluster/README.md
  tools/stress-cluster/cluster/cluster/acr.bicep
  tools/stress-cluster/cluster/cluster/cluster.bicep
  tools/stress-cluster/cluster/cluster/keyvault.bicep
  tools/stress-cluster/cluster/main.bicep
  tools/stress-cluster/cluster/manifests/secret-class-template.yaml
  tools/stress-cluster/cluster/manifests/secret-test.yaml
  tools/stress-cluster/cluster/monitoring/app-insights.bicep
  tools/stress-cluster/cluster/monitoring/log-analytics-workspace.bicep
  tools/stress-cluster/cluster/parameters/dev.json
  tools/stress-cluster/cluster/parameters/prod.json
  tools/stress-cluster/cluster/parameters/test.json
Labels: Central-EngSys

#1701 Hide approve button if diff is not against approved version
  src/dotnet/APIView/APIViewWeb/Models/ReviewRevisionModel.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: APIView, Central-EngSys

#1729 Check for API review status only if release date is set in changelog
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: APIView, Central-EngSys, auto-merge

#1736 Add Ubuntu 20 to local dns bypass template
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, auto-merge

#1739 Update references from master to main
  README.md
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/update-docs-metadata.ps1
  tools/notification-configuration/github-codeowner-subscriber/GitHubService.cs
Labels: auto-merge

#1656 LLCsupport in APIView
  src/dotnet/APIView/APIViewWeb/Languages/ProtocolLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
  src/dotnet/APIView/APIViewWeb/Startup.cs
Labels: APIView, Central-EngSys

#1750 Show last revision name as current review name
  src/dotnet/APIView/APIViewWeb/Client/css/site.scss
  src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
Labels: Central-EngSys

#1753 UI changes
  src/dotnet/APIView/APIViewWeb/Client/css/site.scss
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
Labels: APIView, Central-EngSys

#1725 eng/common changes for docs metadata release
  eng/common/pipelines/templates/steps/enable-long-path-support.yml
  eng/common/pipelines/templates/steps/set-daily-docs-branch-name.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Save-Package-Properties.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge

#1759 Update devops workitem helpers
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: auto-merge

#1757 Add BodyRegexSanitizer and HeaderRemoverSanitizer
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminFunctionalityTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordedTestSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyRegexSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/RemoveHeaderSanitizer.cs
Labels: Central-EngSys

#1763 Disable release date check
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, auto-merge
