Repository Azure/azure-sdk-tools, pull requests merged in 2021-12, with the labels that each got.

#2355 Namespace changed for the chaos-mesh svc
  tools/stress-cluster/chaos/README.md
Labels: auto-merge

#2248 Exclude certain live test deployment outputs from being marked as log secrets
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/build-test-resource-config.yml
Labels: Central-EngSys

#2352 Add spell check pin changes
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: auto-merge

#2372 Restore deploymentOutputs variable in scope for post deployment script
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#2375 Fixing nested copy items in prepare.ps1 for stress test
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/prepare.ps1
Labels: Central-EngSys

#2380 Add PowerShell Script for Validating READMEs
  eng/common/scripts/Verify-Readme.ps1
Labels: auto-merge

#2327 Make changes on docker validation
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge

#2381 Add disk metrics script and template
  eng/common/pipelines/templates/steps/write-filesystemmetrics.yml
  eng/common/scripts/Write-FileSystemMetrics.ps1
Labels: auto-merge

#2363 Use stress test environment defaults for group and subscription
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  eng/pipelines/stress-test-release.yml
  tools/stress-cluster/chaos/examples/network-stress-example/templates/testjob.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/Dockerfile
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/test-resources-post.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/provision.ps1
Labels: auto-merge, Central-EngSys, Stress

#2393 Taking the parameter literally
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: auto-merge

#2402 Added new API to get list of github issues
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: auto-merge, Central-EngSys

#2397 Handle Bad Incoming Regex, Ensure that we throw the appropriate exception out of Admin/CreateInstance method
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/StringSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyRegexSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/GeneralRegexSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/HeaderRegexSanitizer.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/UriRegexSanitizer.cs
Labels: Central-EngSys

#2407 Update azure deployer init container name in stress README
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys, Stress

#2408 [stress] Use named parameter arguments and explicitly set switch argument values
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress

#2376 Preprocess api file in devops pipeline for Python
  src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
  src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
  src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
  src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: Central-EngSys

#2410 [Test-Proxy] Address Empty-Body-Stream Error
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Labels: Central-EngSys

#2406 [Test-Proxy] Match any URI Order
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/request_with_subscriptionid.json
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/CustomDefaultMatcher.cs
Labels: Central-EngSys

#2412 [TestResources] Ensure ownership grant
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Client, auto-merge

#2415 Added more parameter for JS use
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#2417 Update Verify Readme logic
  eng/common/pipelines/templates/steps/verify-readme.yml
  eng/common/scripts/Verify-Readme.ps1
Labels: auto-merge

#2409 Add chaos resource debugging to readme
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys, Stress

#2442 Increase GitHub get issues fetch limit
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: auto-merge, Central-EngSys

#2458 Package Python 3.9 in apiview deployment
  .azure-pipelines/apiview.yml
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/_apiview.py
  packages/python-packages/api-stub-generator/apistub/_version.py
Labels: Central-EngSys

#2447 Preserve kubectl context namespace if set for active stress cluster
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress
