Repository Azure/azure-sdk-tools, pull requests merged in 2021-07, with the labels that each got.

#1768 Update docs metadata mutation logic
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#1772 Update change log headers based on guideline update
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: auto-merge

#1769 Initial Protocol API View
  packages/python-packages/protocol-stub-generator/CHANGELOG.md
  packages/python-packages/protocol-stub-generator/MANIFEST.in
  packages/python-packages/protocol-stub-generator/README.md
  packages/python-packages/protocol-stub-generator/protocol/__init__.py
  packages/python-packages/protocol-stub-generator/protocol/_diagnostic.py
  packages/python-packages/protocol-stub-generator/protocol/_token.py
  packages/python-packages/protocol-stub-generator/protocol/_token_kind.py
  packages/python-packages/protocol-stub-generator/protocol/_version.py
  packages/python-packages/protocol-stub-generator/protocol/parse_yml.py
  packages/python-packages/protocol-stub-generator/protocol/protocol_models.py
  packages/python-packages/protocol-stub-generator/protocolGen.py
  packages/python-packages/protocol-stub-generator/setup.cfg
  packages/python-packages/protocol-stub-generator/setup.py
  packages/python-packages/protocol-stub-generator/tox.ini
Labels: APIView, LLCView

#1761 Add stress test "package" format, official cluster deployments
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/chaos/examples/network_loss.yaml
  tools/stress-cluster/chaos/examples/network_stress_example/Chart.lock
  tools/stress-cluster/chaos/examples/network_stress_example/Chart.yaml
  tools/stress-cluster/chaos/examples/network_stress_example/Dockerfile
  tools/stress-cluster/chaos/examples/network_stress_example/install.sh
  tools/stress-cluster/chaos/examples/network_stress_example/poll.sh
  tools/stress-cluster/chaos/examples/network_stress_example/templates/network_loss.yaml
  tools/stress-cluster/chaos/examples/network_stress_example/templates/testjob.yaml
  tools/stress-cluster/chaos/examples/stress_deployment_example/.gitignore
  tools/stress-cluster/chaos/examples/stress_deployment_example/Chart.lock
  tools/stress-cluster/chaos/examples/stress_deployment_example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress_deployment_example/install.sh
  tools/stress-cluster/chaos/examples/stress_deployment_example/parameters.json
  tools/stress-cluster/chaos/examples/stress_deployment_example/templates/deploy-job.yaml
  tools/stress-cluster/chaos/examples/stress_deployment_example/test-resources.bicep
  tools/stress-cluster/chaos/examples/testjob.yaml
  tools/stress-cluster/cluster/README.md
  tools/stress-cluster/cluster/azure/cluster/acr.bicep
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
  tools/stress-cluster/cluster/azure/cluster/keyvault.bicep
  tools/stress-cluster/cluster/azure/cluster/static-vault-access-policy.bicep
  tools/stress-cluster/cluster/azure/main.bicep
  tools/stress-cluster/cluster/azure/monitoring/app-insights.bicep
  tools/stress-cluster/cluster/azure/monitoring/log-analytics-workspace.bicep
  tools/stress-cluster/cluster/azure/parameters/dev.json
  tools/stress-cluster/cluster/azure/parameters/prod.json
  tools/stress-cluster/cluster/azure/parameters/test.json
  tools/stress-cluster/cluster/kubernetes/README.md
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/.helmignore
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/values.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/.gitignore
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/.helmignore
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.sh
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_container_env.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_deploy_configmap.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_deploy_volumes.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_env_volumes.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_env.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_util.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-cluster-secret-provider.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-static-secret-provider.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
  tools/stress-cluster/cluster/manifests/secret-class-template.yaml
  tools/stress-cluster/cluster/manifests/secret-test.yaml
Labels: Central-EngSys

#1782 Switch ubuntu 18 to ubuntu 20
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: auto-merge

#1767 Support building and deploying bicep templates
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, auto-merge

#1784 Update readme to use from-pod template
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys

#1786 LL parser support to create protocol API review from autorest yaml
  .azure-pipelines/apiview.yml
  packages/python-packages/protocol-stub-generator/protocol/parse_yml.py
  packages/python-packages/protocol-stub-generator/setup.py
  src/dotnet/APIView/APIViewWeb/Languages/ProtocolLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
Labels: APIView, Central-EngSys, LLCView

#1780 Add root directory to list of sparse checkout paths
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: auto-merge

#1793 Fixing Issue with Definition ID
  packages/python-packages/protocol-stub-generator/protocol/parse_yml.py
  packages/python-packages/protocol-stub-generator/protocol/protocol_models.py
Labels: APIView

#1808 Add FilterPoliCheckResult.ps1
  eng/common/scripts/FilterPoliCheckResults.ps1
Labels: auto-merge

#1748 Simplify Ubuntu image name check for dns bypass
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, auto-merge

#1783 Swift API View
  .gitignore
  src/swift/.gitignore
  src/swift/Info.plist
  src/swift/README.md
  src/swift/Sources/APIViewManager.swift
  src/swift/Sources/CommandLineArguments.swift
  src/swift/Sources/Extensions/DeclarationModifier+Extensions.swift
  src/swift/Sources/Models/NavigationItem.swift
  src/swift/Sources/Models/NavigationTags.swift
  src/swift/Sources/Models/TokenFile.swift
  src/swift/Sources/Models/TokenItem.swift
  src/swift/Sources/Models/TypeModel.swift
  src/swift/Sources/SourceCodeExample.swift
  src/swift/Sources/Util/Logger.swift
  src/swift/Sources/Util/URL+Extensions.swift
  src/swift/Sources/main.swift
  src/swift/SwiftAPIView.xcodeproj/project.pbxproj
  src/swift/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView on Terminal.xcscheme
  src/swift/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
  src/swift/SwiftAPIView.xcodeproj/xcuserdata/travisprescott.xcuserdatad/xcschemes/xcschememanagement.plist
  src/swift/Tests/Info.plist
  src/swift/Tests/SwiftAPIViewTests.swift
Labels: APIView

#1829 GitHub Label Management
  scripts/python/repo_labels/README.md
  scripts/python/repo_labels/github_labels.txt
  scripts/python/repo_labels/github_repos.txt
  scripts/python/repo_labels/label_tool.py
  tools/github-labels/README.md
  tools/github-labels/common-labels.csv
  tools/github-labels/deploy-labels.ps1
  tools/github-labels/ghcreator/CommandLine.dll
  tools/github-labels/ghcreator/ComposableAsync.Core.dll
  tools/github-labels/ghcreator/CsvHelper.dll
  tools/github-labels/ghcreator/GHCreator.deps.json
  tools/github-labels/ghcreator/GHCreator.dll
  tools/github-labels/ghcreator/GHCreator.runtimeconfig.dev.json
  tools/github-labels/ghcreator/GHCreator.runtimeconfig.json
  tools/github-labels/ghcreator/Octokit.dll
  tools/github-labels/ghcreator/OutputColorizer.dll
  tools/github-labels/ghcreator/RateLimiter.dll
  tools/github-labels/refresh-snapshots.ps1
  tools/github-labels/repositories.txt
  tools/github-labels/repository-snapshots/autorest.csharp.csv
  tools/github-labels/repository-snapshots/autorest.csv
  tools/github-labels/repository-snapshots/autorest.go.csv
  tools/github-labels/repository-snapshots/autorest.java.csv
  tools/github-labels/repository-snapshots/autorest.python.csv
  tools/github-labels/repository-snapshots/autorest.swift.csv
  tools/github-labels/repository-snapshots/autorest.typescript.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-c-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-c.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-cpp.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-go-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-go.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-java-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-java.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-js-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-js.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-net-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-net.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-python-pr.csv
  tools/github-labels/repository-snapshots/azure-sdk-for-python.csv
  tools/github-labels/repository-snapshots/perks.csv
  tools/github-labels/scan-new-labels.ps1
Labels: GitHub Issues

#1839 [Test-Proxy] Need to expose all headers, not just allow them
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
Labels: Central-EngSys

#1827 Update Article Type for Docs.MS Doc Updates
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/update-docs-metadata.ps1
  scripts/powershell/update-docrepo-from-source.ps1
Labels: Central-EngSys, auto-merge

#1807 hotfix release should check all approved revisions
  .azure-pipelines/apiview.yml
  src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
Labels: Central-EngSys

#1848 Add basic ga tag w/ settable campaignid
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/templates/matthews/partials/head.tmpl.partial
Labels: auto-merge

#1842 Generalize CacheChunkOrderingFailureClassifier to handle failures
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/CacheChunkOrderingFailureClassifier.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/CacheFailureClassifier.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
Labels: Central-EngSys

#1850 Update help text for go API review
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
Labels: APIView, Central-EngSys

#1847 Verify API surface level against all approved revisions for GA releases
  eng/common/scripts/Create-APIReview.ps1
Labels: APIView, Central-EngSys, auto-merge

#1856 Fix two Java APIView issues
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Labels: APIView

#1851 Initial scripts and pipeline for stress test discovery/build/push
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/pipelines/stress-test-release.yml
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/network-stress-example/Dockerfile
  tools/stress-cluster/chaos/examples/network-stress-example/install.sh
  tools/stress-cluster/chaos/examples/network-stress-example/poll.sh
  tools/stress-cluster/chaos/examples/network-stress-example/templates/network_loss.yaml
  tools/stress-cluster/chaos/examples/network-stress-example/templates/testjob.yaml
  tools/stress-cluster/chaos/examples/network_stress_example/Dockerfile
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/install.sh
  tools/stress-cluster/chaos/examples/stress-deployment-example/parameters.json
  tools/stress-cluster/chaos/examples/stress-deployment-example/templates/deploy-job.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/test-resources.bicep
  tools/stress-cluster/chaos/examples/stress-deployment-example/test-resources.json
  tools/stress-cluster/chaos/examples/stress_deployment_example/.gitignore
  tools/stress-cluster/cluster/README.md
  tools/stress-cluster/cluster/azure/parameters/prod.json
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/.gitignore
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.sh
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
Labels: auto-merge

#1862 Set default commitish to main for stress test release
  eng/pipelines/stress-test-release.yml
Labels: Central-EngSys
