Repository Azure/azure-sdk-tools, pull requests merged in 2021-04, with the labels that each got.

#1525 Use SubscriptionId throughout TestResources
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/TestResources/Update-TestResources.cmd
  eng/common/TestResources/Update-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1.md
Labels: auto-merge

#1535 Use single quotes for matrix generator command line arguments
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
Labels: Central-EngSys, auto-merge

#1546 Fix BaseName initialization
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: auto-merge

#1548 Remove passing -Mode Complete to deployment
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: auto-merge

#1515 Add lease to runs.
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
Labels: Central-EngSys, EngSys, auto-merge

#1534 Removed the update CI target packages step.
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/update-docs-ci.ps1
Labels: auto-merge

#1504 Enable CI triggers on internal pipelines.
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
Labels: Central-EngSys, EngSys, auto-merge

#1553 Remove condition.
  eng/common/pipelines/templates/steps/retain-run.yml
Labels: auto-merge

#1552 Onboarding branch needs to delete the step of updating target ci
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: auto-merge

#1551 make -checkout: none an optional phase
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: auto-merge

#1557 Call bypass-local-dns.yml from verify-agent-os.yml
  eng/common/pipelines/templates/steps/verify-agent-os.yml
Labels: auto-merge

#1555 Verify samples during CIs
  eng/common/pipelines/templates/steps/verify-samples.yml
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: auto-merge

#1559 Handle empty files in Test-SampleMetadata
  eng/common/pipelines/templates/steps/verify-samples.yml
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: auto-merge

#1560 Add template to merge multiple subscription configurations
  eng/common/TestResources/build-test-resource-config.yml
Labels: Central-EngSys, auto-merge

#1563 Use underscore-prefixed variable name when setting sub config values as secrets
  eng/common/TestResources/build-test-resource-config.yml
Labels: auto-merge

#1544 Fix notification subscriber teams
  tools/notification-configuration/common/Helpers/GitHubNameResolver.cs
  tools/notification-configuration/common/Services/AzureDevOpsService.cs
  tools/notification-configuration/github-codeowner-subscriber/GitHubService.cs
  tools/notification-configuration/github-codeowner-subscriber/Program.cs
  tools/notification-configuration/github-codeowner-subscriber/github-codeowner-subscriber.csproj
  tools/notification-configuration/identity-resolver/Program.cs
  tools/notification-configuration/identity-resolver/identity-resolver.csproj
  tools/notification-configuration/notification-creator/NotificationConfigurator.cs
  tools/notification-configuration/notification-creator/Program.cs
  tools/notification-configuration/notification-creator/notification-creator.csproj
Labels: Central-EngSys

#1564 Stop filtering projects by ci.yml files
  eng/common/scripts/Package-Properties.ps1
Labels: auto-merge

#1558 Set default branch to master if not set from git
  eng/common/pipelines/templates/steps/set-default-branch.yml
Labels: Central-EngSys, auto-merge

#1565 Fix retain runs auth.
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
Labels: Central-EngSys, EngSys, auto-merge

#1562 Add caching support to verify-links
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
  eng/pipelines/githubio-linkcheck.yml
Labels: auto-merge

#1575 Add classifier for Azure Artifacts 503 errors.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/AzureArtifactsServiceUnavailableClassifier.cs
Labels: Central-EngSys, EngSys

#1580 Parse MD files coming over http as raw markdown files
  eng/common/scripts/Verify-Links.ps1
Labels: auto-merge

#1577 Set multiple sparse checkout paths in one command/job
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, auto-merge

#1584 Sync Devops helper scripts from azure-sdk repo
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: auto-merge

#1578 DNS resolution failure classifier.
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/DnsResolutionFailureClassifier.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
Labels: Central-EngSys, EngSys

#1572 Change from master to main for pipeline generation.
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/pipelines/pipeline-generation.yml
Labels: Central-EngSys, EngSys, M2M, Pipeline Generator, auto-merge
