Repository Azure/azure-sdk-tools, pull requests merged in 2022-04, with the labels that each got.

#3047 [stress testing] Fail helm deployments when ARM template does not exist
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_deploy_configmap.tpl
Labels: Central-EngSys, Stress

#2967 Fix bug where job matrices with leading numbers generated duplicate job names
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: auto-merge, Central-EngSys

#2966 Support nested service directories for local test resources resource group names
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#2999 Server-side changes to support collapsible panel in APIVIew
  src/dotnet/APIView/APIView/CodeFileRenderer.cs
  src/dotnet/APIView/APIView/CodeLine.cs
  src/dotnet/APIView/APIView/Model/CodeFileTokenKind.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
  src/dotnet/APIView/apiview_token_gist.json
Labels: Central-EngSys

#3038 Revert pinning python parser using git release tag
  .azure-pipelines/apiview.yml
Labels: Central-EngSys

#3046 Do not rotate SP credential if it already exists when deploying stress clusters
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys, Stress

#3086 Run API stub generator using published package
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/__init__.py
  packages/python-packages/api-stub-generator/apistub/__main__.py
  packages/python-packages/api-stub-generator/apistub/_version.py
  src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Labels: Central-EngSys

#3092 Wait for test proxy startup
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge, Central-EngSys

#3067 Support resource group name override in remove test resources template
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/Update-TestResources.ps1
  eng/common/TestResources/remove-test-resources.yml
Labels: auto-merge, Central-EngSys

#2998 Add missing content to Go API reviews
  src/go/cmd/api_view.go
  src/go/cmd/content.go
  src/go/cmd/content_test.go
  src/go/cmd/models.go
  src/go/cmd/module.go
  src/go/cmd/pkg.go
  src/go/cmd/token_builders.go
  src/go/go.mod
  src/go/go.sum
Labels: APIView, Go

#2963 Verify Changelog Like ForRelease
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: auto-merge, Central-EngSys

#2942 Update pipeline-generator pipelines to set managed variables in generated pipelines
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/pipelines/pipeline-generation.yml
Labels: auto-merge

#3123 Fixed to use the right variable syntax
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge

#3124 Do not fail remove test resources step when env var is not set.
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: auto-merge, Central-EngSys

#3125 [Test-Proxy] Taking advantage of new boolean switch that will dump configuration
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
  tools/test-proxy/docker/dockerfile
  tools/test-proxy/docker/dockerfile-win
Labels: Central-EngSys

#3000 Github io docs sort by client, mgmt, track2, track1
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: auto-merge, Central-EngSys

#3145 Support BaseName overrides in CI mode for New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#3027 Improve the notifications performance
  tools/identity-resolution/Services/GitHubService.cs
  tools/identity-resolution/identity-resolution.csproj
  tools/notification-configuration/notification-creator/NotificationConfigurator.cs
  tools/notification-configuration/notification-creator/Program.cs
Labels: Central-EngSys

#3127 [stress testing] Add resource group name to helm context. Add chaos wrapper.
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_chaos.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_container_env.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_env_volumes.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_env.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_util.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-cluster-secret-provider.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-file-share-secret-provider.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-static-secret-provider.yaml
Labels: Central-EngSys, Stress

#3153 Do not pass "Generated" to live tests as BaseName
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/deploy-test-resources.yml
Labels: auto-merge

#3160 Sort by service name first
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: auto-merge

#3178 Add helm file plugin and local dependency chart usage readme
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/file-plugin/README.md
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/file-plugin/bin/file.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/file-plugin/plugin.yaml
Labels: Central-EngSys, Stress

#3078 Moving Pylint guidelines checker from sdk-for-python to here
  eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
  packages/python-packages/api-stub-generator/ci.yml
  tools/pylint-extensions/pylint-guidelines-checker/README.md
  tools/pylint-extensions/pylint-guidelines-checker/__init__.py
  tools/pylint-extensions/pylint-guidelines-checker/ci.yml
  tools/pylint-extensions/pylint-guidelines-checker/dev_requirements.txt
  tools/pylint-extensions/pylint-guidelines-checker/pylint_guidelines_checker.py
  tools/pylint-extensions/pylint-guidelines-checker/setup.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/__init__.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/__init__.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/api_version_checker_acceptable_class.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/api_version_checker_acceptable_init.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/api_version_checker_violation.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/copyright_header_acceptable.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/copyright_header_violation.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/enum_checker_acceptable.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/enum_checker_violation.py
  tools/pylint-extensions/pylint-guidelines-checker/tests/test_pylint_custom_plugins.py
Labels: Central-EngSys

#3169 Use the batch version of ValidateDocsMsPackagesFn
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#3185 [sdk-generation-package] Bump `colors.js` dependency to address CG alert
  tools/sdk-generation-pipeline/packages/sdk-generation-lib/package.json
Labels: dependencies, javascript

#3188 Skip azcopy download if it already exists
  eng/common/pipelines/templates/steps/publish-blobs.yml
Labels: auto-merge

#3210 [pylint] Fixing pylint warning format
  tools/pylint-extensions/pylint-guidelines-checker/pylint_guidelines_checker.py
Labels: Python

#3175 [Test-Proxy] Adding Redirect Mode
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Info.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Labels: Central-EngSys

#3212 [Test-Proxy] Consume Newest Version of the Test-Proxy in eng/common
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
  tools/test-proxy/docker/README.md
Labels: auto-merge

#3238 [Test-Proxy] Pin proxy version to one that properly sets ListenOptions
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
Labels: auto-merge

#3221 Make docs.ms link relative link
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge, Central-EngSys

#3237 [pylint] adding contibution file
  tools/pylint-extensions/pylint-guidelines-checker/contribution.md
Labels: pylint, pylint priority 1

#3061 Remove daily docs branches
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/pipelines/branch-cleanup.yml
Labels: auto-merge, Central-EngSys

#3250 Fixed bug of deleting more than expected.
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: auto-merge

#3252 [Python Dev Feed] Create Pipeline Definition for uploading packages from PyPI
  eng/pipelines/mirror-pypi-to-dev-feed.yml
  eng/scripts/download_targeted_packages.py
  eng/scripts/download_targeted_packages_requirements.txt
Labels: Central-EngSys
