Repository Azure/azure-sdk-tools, pull requests merged in 2022-06, with the labels that each got.

#3387 Fix apiviewgo cross-platform path handling
  src/go/README.md
  src/go/cmd/api_view_test.go
  src/go/cmd/module.go
  src/go/cmd/pkg.go
  src/go/cmd/testdata/test_alias_export/go.mod
  src/go/cmd/testdata/test_alias_export/internal/exported/source.go
  src/go/cmd/testdata/test_alias_export/test.go
  src/go/cmd/testdata/test_external_alias_exporter/go.mod
  src/go/cmd/testdata/test_external_alias_exporter/test.go
  src/go/cmd/testdata/test_external_alias_source/go.mod
  src/go/cmd/testdata/test_external_alias_source/test.go
  src/go/cmd/testdata/test_service_group/group/internal/go.mod
  src/go/cmd/testdata/test_service_group/group/internal/test.go
  src/go/cmd/testdata/test_service_group/group/test_alias_export/go.mod
  src/go/cmd/testdata/test_service_group/group/test_alias_export/test.go
  src/go/go.mod
  src/go/go.sum
Labels: APIView, Go

#3381 Disable detached head warnings on sparse checkout to commit
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: auto-merge, Central-EngSys

#3392 Fix issue where matrix replace was not using imported display names
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: auto-merge, Central-EngSys

#3383 Remove unused import
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: auto-merge

#3401 Skip component governance for stress test release
  eng/pipelines/stress-test-release.yml
Labels: Central-EngSys, Stress

#3405 Bump retry count on test resource script login
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#3411 Remove backoff in live test cleanup retry
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#3288 Implementing Filtering and Paging for the Reviews Page
  .gitignore
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Client/css/site.scss
  src/dotnet/APIView/APIViewWeb/Client/package.json
  src/dotnet/APIView/APIViewWeb/Client/src/api.ts
  src/dotnet/APIView/APIViewWeb/Client/src/main.ts
  src/dotnet/APIView/APIViewWeb/Client/src/reviews.ts
  src/dotnet/APIView/APIViewWeb/Client/webpack.config.js
  src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
  src/dotnet/APIView/APIViewWeb/Models/UserPreferenceModel.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/ReviewLayout.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewsPartial.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_SelectPickerPartial.cshtml
  src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
  src/dotnet/APIView/APIViewWeb/Repositories/UserPreferenceCache.cs
  src/dotnet/APIView/APIViewWeb/wwwroot/icons/json-original.svg
  src/dotnet/APIView/APIViewWeb/wwwroot/icons/kotlin-original.svg
  src/dotnet/APIView/APIViewWeb/wwwroot/icons/swagger-original.svg
  src/dotnet/APIView/APIViewWeb/wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.js.map
  src/dotnet/APIView/APIViewWeb/wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.min.js.map
  src/dotnet/APIView/APIViewWeb/wwwroot/lib/bootstrap/dist/js/bootstrap.js.map
  src/dotnet/APIView/APIViewWeb/wwwroot/lib/bootstrap/dist/js/bootstrap.min.js.map
  src/dotnet/APIView/APIViewWeb/wwwroot/reviews.js
  src/dotnet/APIView/APIViewWeb/wwwroot/reviews.js.map
Labels: EngSys, Central-EngSys

#3433 [APIView] Disable build step `Create API Review` for private repos
  eng/common/pipelines/templates/steps/create-apireview.yml
Labels: APIView, auto-merge, Central-EngSys

#3267 Update service level readme
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/common.ps1
Labels: Docs, auto-merge, Central-EngSys

#3386 Update the order of remarks and examples to align with docs.ms
  eng/common/docgeneration/templates/matthews/partials/class.header.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.tmpl.partial
Labels: auto-merge, Central-EngSys

#3402 Ensure Credscan job works properly even when wonkiness is auto-injected
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge, Central-EngSys

#3435 Resolve Accesibility issues
  src/dotnet/APIView/APIViewWeb/Client/css/site.scss
  src/dotnet/APIView/APIViewWeb/Client/src/comments.ts
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewsPartial.cshtml
Labels: Central-EngSys

#3417 Convert Pipeline Witness to webapp
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-webapp.yml
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness.Tests/Azure.Sdk.Tools.PipelineWitness.Tests.csproj
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Azure.Sdk.Tools.PipelineWitness.csproj
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/BlobUploadProcessor.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Controllers/PingController.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Entities/AzurePipelines/Run.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Entities/AzurePipelines/RunReason.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Entities/AzurePipelines/RunResult.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Entities/AzurePipelines/RunStatus.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Functions/PingFunction.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Functions/RunStateChangedFunction.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/PipelineWitnessSettings.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Program.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/RunProcessor.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/BuildCompleteQueueWorker.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/BuildLogBundleQueueWorker.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/FailureAnalyzer.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/QueueWorkerBackgroundService.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.development.json
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.json
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.staging.json
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/host.json
  tools/pipeline-witness/ci.yml
Labels: Central-EngSys

#3436 Refactor `Client`/Transport Options to be an overridable option
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ModifiableRecordSession.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Labels: Central-EngSys

#3447 Force error on failure to install Az
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/Dockerfile
Labels: Central-EngSys, Stress

#3457 Add ResourceType parameter
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
Labels: auto-merge

#3453 Fix Bug in Resource Ref Verifier
  eng/common/scripts/Verify-Resource-Ref.ps1
Labels: auto-merge

#3481 Stress development maturity updates
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  eng/pipelines/stress-cluster-provision.yml
  eng/pipelines/stress-test-release.yml
  eng/pipelines/templates/jobs/stress-cluster-provision.yml
  eng/pipelines/templates/jobs/stress-test-release.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/network-stress-example/templates/network_loss.yaml
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/ci.yml
  tools/stress-cluster/cluster/provision.ps1
Labels: auto-merge, Central-EngSys, Stress

#3498 Fix missing what if command argument in stress provision
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys, Stress

#3509 Fail if the emulator doesn't start
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
Labels: auto-merge

#3510 Update the verify-readme script/template to take a single or multiple paths
  eng/common/pipelines/templates/steps/verify-readme.yml
  eng/common/scripts/Verify-Readme.ps1
Labels: auto-merge, Central-EngSys

#3517 [APIView] Java - Expose annotations on enums and upgrade dependencies
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
Labels: APIView

#3482 stress test playground cluster buildout
  tools/stress-cluster/cluster/README.md
  tools/stress-cluster/cluster/azure/.gitignore
  tools/stress-cluster/cluster/azure/parameters/pg.json
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
Labels: Central-EngSys

#3491 stress test script and docs migration from test to pg cluster
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/cluster/azure/main.bicep
  tools/stress-cluster/cluster/azure/monitoring/stress-status-workbook.bicep
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
Labels: auto-merge, Central-EngSys, Stress

#3528 Update stress test ci to include PR paths
  tools/stress-cluster/ci.yml
Labels: Central-EngSys, Stress

#3519 [stress-testing] Flexible resource naming: add BaseName to stress-test-addons helm context
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/stress-test-resources.bicep
  tools/stress-cluster/chaos/examples/stress-deployment-example/templates/deploy-job.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_util.tpl
Labels: Central-EngSys, Stress

#3537 Deploy stress CI to pg environment
  eng/pipelines/templates/jobs/stress-test-release.yml
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
  tools/stress-cluster/ci.yml
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys, Stress
