Repository Azure/azure-sdk-tools, pull requests merged in 2022-01, with the labels that each got.

#2464 Support AAD graph and Microsoft Graph service principal APIs
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge

#2499 Update ApiView to Check for new Codesnippet Tag
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavadocCodeSnippetsRule.java
Labels: APIView, Java

#2484 [pipeline generator] Build out weekly test pipelines for all services and fix scheduling
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/pipelines/pipeline-generation.yml
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/ExitCondition.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/PipelineGenerationContext.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
Labels: auto-merge, Central-EngSys

#2416 Remove cluster group and subscription overrides for stress test release
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  eng/pipelines/stress-test-release.yml
Labels: auto-merge, Central-EngSys, Stress

#2502 Overwrite existing internal PR branch filters in yaml override mode
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
Labels: Central-EngSys

#2498 Add Root Directory and Glob for Injecting Snippets into READMEs
  packages/java-packages/codesnippet-maven-plugin/pom.xml
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/SnippetBaseMojo.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
Labels: Java

#2500 Update pipeline generator tool version
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: auto-merge, Central-EngSys

#2519 Fix PR detection bad request issue
  src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
Labels: Central-EngSys

#2538 Don't Fail codesnippet-maven-plugin when Sources Don't Exist
  packages/java-packages/codesnippet-maven-plugin/pom.xml
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
Labels: Java

#2513 Update test resources SP password creation to support Az >= 7.1.0
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#2551 [Python APIView] fix typehint parsing in Python 3.10
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/_version.py
  packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_typehint_parser.py
  packages/python-packages/api-stub-generator/tests/function_parsing_test.py
  packages/python-packages/api-stub-generator/tests/typehint_parser_test.py
Labels: APIView, Python

#2554 Update image tag and version at eng/common for proxy tool
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge

#2545 fix: body is too long when create github release
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: auto-merge

#2560 Add property in review page to get reviews by service/package name group
  src/dotnet/APIView/APIViewWeb/Controllers/ReviewController.cs
  src/dotnet/APIView/APIViewWeb/Models/ReviewDisplayModel.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: APIView, Central-EngSys

#2563 Force add SwiftAPIView.xcworkspace and tweak gitignore
  .gitignore
  src/swift/.gitignore
  src/swift/SwiftAPIView.xcworkspace/contents.xcworkspacedata
  src/swift/SwiftAPIView.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: APIView, Client, Swift

#2562 Apiview readme
  src/dotnet/APIView/APIViewWeb/README.md
Labels: Central-EngSys

#2573 [stress testing] Upgrade kubernetes cluster version to 1.22.4
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
Labels: Central-EngSys, Stress

#2577 Contributing guide for APIView
  src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
Labels: APIView, Central-EngSys

#2586 [Swift APIView] Improve definition ID creation
  src/swift/SwiftAPIView.xcworkspace/contents.xcworkspacedata
  src/swift/SwiftAPIViewCore/Sources/Extensions/DeclarationModifier+Extensions.swift
  src/swift/SwiftAPIViewCore/TestFiles/TestFile2.swifttxt
Labels: bug, APIView, Swift

#2561 [stress tests] Add acr login to quick getting started steps
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys, Stress

#2592 Only fetch provision application oid via API if not supplied
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#2590 [Python APIView] Fix inconsistent line spacing issues
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/_apiview.py
  packages/python-packages/api-stub-generator/apistub/_stub_generator.py
  packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
  packages/python-packages/api-stub-generator/setup.py
  packages/python-packages/api-stub-generator/tests/apiview_test.py
Labels: bug, APIView, Python

#2585 [Test-Proxy] Update targeted version of test-proxy
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge

#2596 Update our retention time to 2 years
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
Labels: auto-merge

#2593 Update codesnippet-maven-plugin
  packages/java-packages/codesnippet-maven-plugin/pom.xml
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/RootAndGlob.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/SnippetBaseMojo.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
Labels: Java

#2578 Removing duplicated env:USER in image tag for stress test
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress

#2570 Set notification team type as a prefix to avoid long name duplicates
  tools/identity-resolution/identity-resolution/Models/TeamMetadata.cs
  tools/identity-resolution/identity-resolution/Services/AzureDevOpsService.cs
  tools/notification-configuration/notification-creator/NotificationConfigurator.cs
Labels: Central-EngSys

#2581 Get ms alias from github identity.
  eng/common/scripts/Get-AADIdentityFromGithubUser.ps1
Labels: auto-merge

#2599 Added configurable docker build directory for stress test
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys

#2597 Add translation, storage subs to zombie resource cleanup
  eng/pipelines/live-test-cleanup.yml
Labels: Central-EngSys

#2611 Use valid characters for notification team name prefix
  tools/notification-configuration/notification-creator/NotificationConfigurator.cs
Labels: Central-EngSys

#2614 Bump notification creator tool version
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys

#2617 remove greedy suffix on link check
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: auto-merge

#2604 fix incidentally added path addition
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: auto-merge

#2601 Add go repo to pipeline failure notification automation
  eng/pipelines/notifications.yml
Labels: Central-EngSys

#2641 Update matrix doc header titles for replace/modify/append
  eng/common/scripts/job-matrix/README.md
Labels: auto-merge, Central-EngSys
