Repository Azure/azure-sdk-tools, pull requests merged in 2022-12, with the labels that each got.

#4856 Use same CustomCondition as success task
  eng/common/pipelines/templates/steps/publish-artifact.yml
Labels: auto-merge

#4837 Move internal wiki page "Subscribe to Notifications" next to tools/notification-configuration
  tools/notification-configuration/README.md
  tools/notification-configuration/notification-configuration.sln
Labels: Central-EngSys

#4878 [Perf] Add profiling to perf automation
  eng/common/pipelines/templates/jobs/perf.yml
  tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Cpp.cs
  tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/ILanguage.cs
  tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
  tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/JavaScript.cs
  tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/LanguageBase.cs
  tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Net.cs
  tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs
  tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Python.cs
  tools/perf-automation/tests.yml
Labels: auto-merge

#4885 Assorted set of minor refactorings for logic related to CODEOWNERS processing
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ConsoleOutput.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/MainTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
  tools/code-owners-parser/CodeOwnersParser.sln
  tools/code-owners-parser/CodeOwnersParser.sln.DotSettings
  tools/code-owners-parser/CodeOwnersParser/CodeOwnerEntry.cs
  tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs
  tools/code-owners-parser/CodeOwnersParser/FileHelpers.cs
  tools/identity-resolution/Services/GitHubService.cs
  tools/notification-configuration/notification-configuration.sln.DotSettings
Labels: Central-EngSys

#4832 CADL manual API review
  eng/pipelines/apiview-review-gen-cadl.yml
  eng/scripts/Create-Apiview-Token-Cadl.ps1
  src/dotnet/APIView/APIViewIntegrationTests/ReviewManagerTests.cs
  src/dotnet/APIView/APIViewWeb/Client/src/reviews.ts
  src/dotnet/APIView/APIViewWeb/Languages/CadlLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Managers/IReviewManager.cs
  src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
  src/dotnet/APIView/APIViewWeb/Models/ReviewGenPipelineParamModel.cs
  src/dotnet/APIView/APIViewWeb/Models/UploadModel.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Startup.cs
Labels: Central-EngSys

#4835 Verify pull request authorization to generate APIreview using OSS man…
  .azure-pipelines/apiview.yml
  src/dotnet/APIView/APIView/APIView.csproj
  src/dotnet/APIView/APIViewIntegrationTests/APIViewIntegrationTests.csproj
  src/dotnet/APIView/APIViewUITests/APIViewUITests.csproj
  src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Account/PullRequestPermissionRequirement.cs
  src/dotnet/APIView/APIViewWeb/Account/PullRequestPermissionRequirementHandler.cs
  src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Managers/CommentsManager.cs
  src/dotnet/APIView/APIViewWeb/Managers/IOpenSourceRequestManager.cs
  src/dotnet/APIView/APIViewWeb/Managers/NotificationManager.cs
  src/dotnet/APIView/APIViewWeb/Managers/OpenSourceRequestManager.cs
  src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs
  src/dotnet/APIView/APIViewWeb/Models/OpenSourceUserInfo.cs
  src/dotnet/APIView/APIViewWeb/Models/PullRequestModel.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/RequestedReviews.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Program.cs
  src/dotnet/APIView/APIViewWeb/Startup.cs
Labels: Central-EngSys

#4813 Fix ApiView-Helpers grammar issue
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: auto-merge

#4921 CADL manual API review additional changes
  eng/pipelines/apiview-review-gen-cadl.yml
  eng/scripts/Create-Apiview-Token-Cadl.ps1
  src/dotnet/APIView/APIViewWeb/Languages/CadlLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml.cs
Labels: Central-EngSys

#4929 [Asset sync] Handle additional git remote format
  tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1
Labels: EngSys, Asset-Sync

#4915 Update PipelineGenerator target framework from netcoreapp3.1 to net6.0
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
  tools/pipeline-generator/ci.yml
Labels: Central-EngSys

#4930 Introduce "job" version of prepare-pipelines.yml, with "pool" defined to use Ubuntu 20.04
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: auto-merge, Central-EngSys

#4941 [testmodeler] upgrade codemodel
  tools/sdk-testgen/common/config/rush/pnpm-lock.yaml
  tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.json
  tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.md
  tools/sdk-testgen/packages/autorest.testmodeler/README.md
  tools/sdk-testgen/packages/autorest.testmodeler/npm-shrinkwrap.json
  tools/sdk-testgen/packages/autorest.testmodeler/package.json
  tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/appplatform-remote/model/__debug/test-modeler-pre.yaml
  tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/appplatform-remote/model/__debug/test-modeler.yaml
  tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/appplatform/model/__debug/test-modeler-pre.yaml
  tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/appplatform/model/__debug/test-modeler.yaml
  tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/testAutorest.ts
Labels: sdk-testgen

#4950 Update doc/common/common_engsys.md
  doc/common/common_engsys.md
  eng/pipelines/eng-common-sync.yml
Labels: Central-EngSys

#4937 Set .NET used by our tools to `net6.0` + minor updates to .sln files
  src/dotnet/APIView/TestLibrary/TestLibrary.csproj
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.sln
  src/dotnet/Azure.ClientSdk.Analyzers/ci.yml
  tools/CreateRuleFabricBot/CreateRuleFabricBot.sln
  tools/CreateRuleFabricBot/CreateRuleFabricBot/CreateRuleFabricBot.csproj
  tools/CreateRuleFabricBot/CreateRuleFabricBotTests/CreateRuleFabricBotTests.csproj
  tools/CreateRuleFabricBot/ci.yml
  tools/agent-time-extractor/AgentTimeExtractor/AgentTimeExtractor.csproj
  tools/apiview/parsers/swagger-api-parser/ci.yml
  tools/apiview/parsers/swagger-api-parser/swagger-api-parser.sln
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/Azure.Sdk.Tools.RetrieveCodeOwners.Tests.csproj
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Azure.Sdk.Tools.RetrieveCodeOwners.csproj
  tools/code-owners-parser/ci.yml
  tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector.sln
  tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Azure.Sdk.Tools.HttpFaultInjector.csproj
  tools/http-fault-injector/ci.yml
  tools/http-fault-injector/sample-clients/net/http-client/Azure.Sdk.Tools.HttpFaultInjector.HttpClientSample.csproj
  tools/http-fault-injector/sample-clients/net/storage-blobs/Azure.Sdk.Tools.HttpFaultInjector.StorageBlobsSample.csproj
  tools/identity-resolution/ci.yml
  tools/identity-resolution/identity-resolution.csproj
  tools/notification-configuration/ci.yml
  tools/notification-configuration/notification-creator/Azure.Sdk.Tools.NotificationConfiguration.csproj
  tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/Azure.Sdk.Tools.SnippetGenerator.Tests.csproj
  tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/Azure.Sdk.Tools.SnippetGenerator.csproj
  tools/snippet-generator/SnippetGenerator.sln
  tools/snippet-generator/ci.yml
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator.Tests/Stress.Generator.Tests.csproj
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Stress.Generator.csproj
  tools/stress-cluster/cluster/kubernetes/generator/ci.yml
  tools/stress-cluster/cluster/kubernetes/generator/generator.sln
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.sln
  tools/test-proxy/sample-clients/net/http-client/Azure.Sdk.Tools.TestProxy.HttpClientSample.csproj
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineSample.csproj
  tools/test-proxy/sample-clients/net/storage-blob/Azure.Sdk.Tools.TestProxy.StorageBlobSample.csproj
  tools/version-guard/Microsoft.Azure.Sdk.Tools.VersionGuard/Microsoft.Azure.Sdk.Tools.VersionGuard.csproj
  tools/version-guard/VersionGuard.sln
  tools/version-guard/ci.yml
  web/pixel-server/PixelServer/PixelServer.csproj
  web/pixel-server/PixelServer/Program.cs
Labels: Central-EngSys

#4944 Helm template for deploy script
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress

#4916 Bump globals.yml .NET SDK version from 3.1.405 to 6.x + assorted changes
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-function.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-webapp.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/variables/globals.yml
  src/dotnet/Azure.ClientSdk.Analyzers/ci.yml
  tools/CreateRuleFabricBot/ci.yml
  tools/apiview/parsers/swagger-api-parser/ci.yml
  tools/code-owners-parser/ci.yml
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues.Tests/Azure.Sdk.Tools.GitHubIssues.Tests.csproj
  tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
  tools/http-fault-injector/ci.yml
  tools/identity-resolution/ci.yml
  tools/notification-configuration/ci.yml
  tools/pipeline-generator/ci.yml
  tools/snippet-generator/ci.yml
  tools/stress-cluster/cluster/kubernetes/generator/ci.yml
  tools/version-guard/ci.yml
Labels: Central-EngSys

#4514 Update the regex to embrace more image names
  eng/common/scripts/Verify-AgentOS.ps1
Labels: auto-merge

#4962 prepare pipeline job bug fix
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: auto-merge

#4984 Migrate Tests.CI.BuildTasks.csproj and Tests.CI.Common.csproj to net6.0
  src/dotnet/Mgmt.CI.BuildTools/CI/CI.BuildTasks/Tests/CI.BuildTasks.Tests/Tests.CI.BuildTasks.csproj
  src/dotnet/Mgmt.CI.BuildTools/CI/CI.Common/Tests/Tests.CI.Common.csproj
Labels: Central-EngSys

#4940 Add load-testing to list of valid sample slugs
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: auto-merge

#4969 Refactor pipeline-generator to use CommandLineParser
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/CommandParserOptions/DefaultOptions.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/CommandParserOptions/GenerateOptions.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/PipelineGenerationContext.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
Labels: Central-EngSys

#4993 Migrate CheckEnforcer and WebhookRouter to net6.0
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer.Tests/Azure.Sdk.Tools.CheckEnforcer.Tests.csproj
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter.Tests/Azure.Sdk.Tools.WebhookRouter.Tests.csproj
  tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
Labels: Central-EngSys

#4988 Batch eng/common changes to wrap-up #4888 work: NuGet package update, obsolete file deletion, test restoration
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/common/scripts/get-codeowners.ps1
  tools/code-owners-parser/ci.yml
Labels: Central-EngSys

#5000 Make pipeline generator variable group flag optional
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/CommandParserOptions/GenerateOptions.cs
Labels: Central-EngSys

#4998 Update pipeline generation yaml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/pipelines/pipeline-generation-single.yml
  eng/pipelines/pipeline-generation.yml
Labels: auto-merge, Central-EngSys

#4880 Migrate from win2019 to new pool win2022
  eng/common/pipelines/templates/jobs/docindex.yml
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/pipelines/apiview-review-gen-swagger.yml
  eng/pipelines/branch-cleanup.yml
  eng/pipelines/eng-common-sync.yml
  eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  src/dotnet/Mgmt.CI.BuildTools/Directory.Build.props
  src/dotnet/Mgmt.CI.BuildTools/ci.yml
  tools/apiview/parsers/cpp-api-parser/ci.yml
  tools/perf-automation/tests.yml
  tools/test-proxy/tests.yml
Labels: auto-merge

#4985 Give the csv flexibility to onboard "not New" package to Docs.Ms
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge, Central-EngSys

#5029 Update `<TargetFramework>netstandard2.0` to `net6.0` in `Azure.ClientSdk.Analyzers` and `CodeOwnersParser`
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
  tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj
Labels: Central-EngSys
