Repository Azure/azure-sdk-tools, pull requests merged in 2022-11, with the labels that each got.

#4579 Fix APIvIew pipeline test failure
  .azure-pipelines/apiview.yml
Labels: Central-EngSys

#4574 10/31 Test Proxy Update
  eng/common/testproxy/target_version.txt
Labels: auto-merge

#4591 Handle helm version modifiers in stress test min version check
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: auto-merge, Central-EngSys, Stress

#4586 Add package source override to toc script.
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: auto-merge

#4583 Regenerate diff metadata when codefile is updated by sandboxing
  src/dotnet/APIView/APIView/Model/CodeFile.cs
  src/dotnet/APIView/APIViewWeb/Controllers/ReviewController.cs
  src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: Central-EngSys

#4603 cspell issues in cpp branch , needs updated node, and cspell and npx …
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/spelling/Invoke-Cspell.ps1
Labels: auto-merge

#4606 "Hybrid Mode" Proxy Updates
  eng/common/testproxy/target_version.txt
Labels: auto-merge

#4633 Add daily 100GB quota for stress log workspace
  tools/stress-cluster/cluster/azure/monitoring/log-analytics-workspace.bicep
Labels: Central-EngSys, Stress

#4622 Add public cloud cosmos endpoint suffix
  eng/common/TestResources/clouds/AzureCloud.json
Labels: auto-merge, Central-EngSys

#4629 [stress testing] Set default LimitRange for stress container resource requests
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress

#4649 Improve Error Page
  src/dotnet/APIView/APIViewWeb/Pages/Error.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Error.cshtml.cs
Labels: Central-EngSys

#4669 Updating check enforcer permissions to enable writing comments
  .github/workflows/event.yml
Labels: Central-EngSys

#4623 Add optional TestResourcesDirectory override parameter
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#4666 Handle possible strict mode bugs
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/ci.yml
Labels: auto-merge, Central-EngSys, Stress

#4631 [stress testing] Warn user when helm fails due to large files not being ignored
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress

#4679 Speed up sync eng/common pipeline
  eng/pipelines/eng-common-sync.yml
Labels: Central-EngSys

#4686 Disable target framework check
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
Labels: Central-EngSys

#4687 Updating target version to one with brotli encoding supported
  eng/common/testproxy/target_version.txt
Labels: auto-merge

#4632 Update index table when generate service level readme
  eng/common-tests/doc-automation/service-readme-generation/Service.Readme.Generation.Helpers.ps1
  eng/common-tests/doc-automation/service-readme-generation/Service.Readme.Generation.Tests.ps1
  eng/common-tests/doc-automation/service-readme-generation/ci.yml
  eng/common-tests/doc-automation/service-readme-generation/inputs/actual/latest/service-name-4-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/actual/latest/service-name-4.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/actual/latest/service-name-7.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/actual/preview/service-name-5-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/actual/preview/service-name-5.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/actual/preview/service-name-6-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/actual/preview/service-name-6.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/latest/service-name-2-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/latest/service-name-2.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/latest/service-name-4-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/latest/service-name-4.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/latest/service-name-7.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/preview/service-name-1-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/preview/service-name-1.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/preview/service-name-3-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/preview/service-name-3.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/preview/service-name-5-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/preview/service-name-5.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/preview/service-name-6-index.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/expected/preview/service-name-6.md
  eng/common-tests/doc-automation/service-readme-generation/inputs/package1.json
  eng/common-tests/doc-automation/service-readme-generation/inputs/package2.json
  eng/common-tests/doc-automation/service-readme-generation/inputs/package3.json
  eng/common-tests/doc-automation/service-readme-generation/inputs/package4.json
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: auto-merge

#4668 [Cadl APIView] Support aliases and augment decorators
  tools/apiview/emitters/cadl-apiview/CHANGELOG.md
  tools/apiview/emitters/cadl-apiview/README.md
  tools/apiview/emitters/cadl-apiview/package.json
  tools/apiview/emitters/cadl-apiview/src/apiview.ts
  tools/apiview/emitters/cadl-apiview/src/namespace-model.ts
  tools/apiview/emitters/cadl-apiview/src/navigation.ts
  tools/apiview/emitters/cadl-apiview/src/version.ts
  tools/apiview/emitters/cadl-apiview/test/apiview.test.ts
Labels: APIView, Cadl

#4701 Change the way of using env var
  eng/common/scripts/Queue-Pipeline.ps1
  eng/pipelines/templates/steps/sync-directory.yml
Labels: auto-merge

#4726 Fix minor issue getting stress secret labels with quoting and error handling
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress

#4730 Transition script not throwing error properly
  tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1
Labels: Asset-Sync

#4628 Add new check in APIView to verify and enforce package name approval
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: auto-merge, Central-EngSys

#4733 Use powershell argument syntax in test proxy transition script
  tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1
Labels: Central-EngSys

#4703 Extend GetReviewStatus to retrieve specific revies via reviewId
  src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
Labels: Central-EngSys

#4728 Use the new audience field
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: auto-merge

#4746 Fix push script passing in optional argument
  eng/common/scripts/git-branch-push.ps1
Labels: auto-merge

#4758 Bring Your Own Proxy Exe
  tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1
Labels: Asset-Sync

#4772 Fix stress watcher to delete test resources on job deletion events
  tools/stress-cluster/services/Stress.Watcher/src/JobEventHandler.cs
  tools/stress-cluster/services/Stress.Watcher/tests/JobEventHandlerTest.cs
Labels: Central-EngSys, Stress

#4713 stress matrix - support for docker args / env variables
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/chaos/README.md
Labels: auto-merge, Central-EngSys, Stress
