Repository Azure/azure-sdk-tools, pull requests merged in 2022-02, with the labels that each got.

#2652 Update stress examples/generator to set imagePullPolicy: Always
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/chaos/examples/network-stress-example/templates/testjob.yaml
  tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Job.cs
Labels: Central-EngSys

#2571 [Python APIView] Support TypedDict
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/nodes/__init__.py
  packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_key_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_property_node.py
  packages/python-packages/api-stub-generator/tests/class_parsing_test.py
Labels: APIView, Client, Python

#2632 Add all reviews for same package display name as entity under review page
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: APIView, Central-EngSys

#2608 Fill ms.author metadata for docs.
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#2661 Updating dashboard bicep files
  tools/stress-cluster/cluster/azure/.gitignore
  tools/stress-cluster/cluster/azure/main.bicep
  tools/stress-cluster/cluster/azure/monitoring/stress-status-workbook.bicep
  tools/stress-cluster/cluster/azure/monitoring/stress-test-workbook.bicep
Labels: Central-EngSys

#2605 Non stop on errors.
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#2677 Resolve null service name
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: APIView, Central-EngSys

#2673 Fixed the failure from strict mode.
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#2675 Auto subscribe to review notifications when adding a comment
  src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
  src/dotnet/APIView/APIViewWeb/Controllers/CommentsController.cs
  src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Delete.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Repositories/AuthorizationFailedException.cs
  src/dotnet/APIView/APIViewWeb/Repositories/CommentsManager.cs
  src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
  src/dotnet/APIView/APIViewWeb/Startup.cs
Labels: Central-EngSys

#2682 [stress testing] Support github user namespaces for codespaces environments
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: auto-merge, Central-EngSys, Stress

#2685 Fixed the no IsPrerelease property issue and retry 3 times on API call.
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#2688 [stress testing] Remove docs that mention parameters.json is required
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys, Stress

#2689 [stress testing] Remove redundant `chart` directory structure in docs
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys, Stress

#2700 Stress status dashboard bug fix & double grid height
  tools/stress-cluster/cluster/azure/monitoring/stress-status-workbook.bicep
Labels: Central-EngSys

#2691 Update prepare-release parameter documentation
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: auto-merge

#2692 Support not recording request body
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordSessionTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/EntryRecordMode.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordTransport.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Labels: auto-merge

#2686 Add common template for credscan step
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge, Central-EngSys

#2663 Add subscription resource management guidelines
  doc/engsys_resource_management.md
Labels: Central-EngSys

#2720 Print example docker commands after building stress image
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress

#2606 Prevent panic on unnamed receiver
  src/go/cmd/content.go
  src/go/cmd/token_builders.go
Labels: APIView, Go

#2728 [stress test] add query button for dashboard
  tools/stress-cluster/cluster/azure/monitoring/stress-test-workbook.bicep
Labels: Central-EngSys

#2679 [test resources] Add max value to DeleteAfter of 168 hours
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: auto-merge, Central-EngSys

#2721 Add catch-all parameter to test resources script
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#2733 Preprocess the target branch + Add checks on delete/rename files
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge

#2693 Added APIView json token gist file
  src/dotnet/APIView/apiview_token_gist.json
Labels: Central-EngSys

#2739 Fixed the regex of the target branch
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge

#2740 Change credscan to use v3 and enable scan entire repo
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge

#2734 Generate weekly unified pipelines. Make variant naming consistent
  eng/pipelines/pipeline-generation.yml
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyUnifiedPipelineConvention.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
Labels: Central-EngSys

#2754 Disable the config of encoding path in git
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge

#2752 Update the github-codeowner-subscriber version
  eng/pipelines/notifications.yml
  eng/pipelines/templates/variables/globals.yml
Labels: Docs, Central-EngSys

#2759 Add logic to generate docs.ms ToC
  eng/common/scripts/Update-DocsMsToc.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge

#2775 Update credscan tool version
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge

#2768 Add timeout on Invoke-request call
  eng/common/scripts/Verify-Links.ps1
Labels: Docs, auto-merge, Central-EngSys

#2765 Update pipeline generator version to 20220211.1 (support upweekly)
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: auto-merge, Central-EngSys

#2788 [Test-Proxy] Fix docker build, ensure docker logging, update generic error responses
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
  tools/test-proxy/docker/dockerfile
  tools/test-proxy/documentation/using-in-devops.md
Labels: Central-EngSys

#2805 Move Set-StrictMode to run after PSModule-Helpers.ps1 operations
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: auto-merge

#2803 Making `docker` automation available to users of `archetype-sdk-tool-dotnet`
  eng/containers/ci.yml
  eng/pipelines/publish-docker-image.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
  tools/test-proxy/ci.yml
Labels: Central-EngSys

#2771 Add Partner Drop Yml Pipelines
  eng/common/scripts/copy-from-blobstorage.ps1
  eng/pipelines/azuresdkpartnerdrops-to-devops.yml
  eng/pipelines/azuresdkpartnerdrops-to-nuget.yml
  eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
Labels: auto-merge, Central-EngSys
