Repository Azure/azure-sdk-tools, pull requests merged in 2022-03, with the labels that each got.

#2778 Clean up unused codes and dependencies
  eng/common/pipelines/templates/steps/credscan.yml
  eng/common/scripts/update-docs-metadata.ps1
  tools/identity-resolution/Enums/TeamPurpose.cs
  tools/identity-resolution/Helpers/GitHubToAADConverter.cs
  tools/identity-resolution/Helpers/StringHelper.cs
  tools/identity-resolution/Helpers/YamlHelper.cs
  tools/identity-resolution/Models/IdentityDetail.cs
  tools/identity-resolution/Models/TeamMetadata.cs
  tools/identity-resolution/Services/AzureDevOpsService.cs
  tools/identity-resolution/identity-converter/Azure.Sdk.Tools.IdentityConverter.csproj
  tools/identity-resolution/identity-converter/Program.cs
  tools/identity-resolution/identity-resolution.csproj
  tools/identity-resolution/identity-resolution/Helpers/GitHubNameResolver.cs
  tools/notification-configuration/github-codeowner-subscriber/Azure.Sdk.Tools.GithubCodeownerSubscriber.csproj
  tools/notification-configuration/github-codeowner-subscriber/Program.cs
  tools/notification-configuration/notification-creator/Azure.Sdk.Tools.NotificationConfiguration.csproj
Labels: auto-merge, Central-EngSys

#2823 [Test-Proxy] Allow debug logging with docker host from CI. Bump targeted test-proxy version. Update versioning methodology.
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge

#2781 [Python APIView] CrossLangugageDefintionId implementation
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/__init__.py
  packages/python-packages/api-stub-generator/apistub/_apiview.py
  packages/python-packages/api-stub-generator/apistub/_diagnostic.py
  packages/python-packages/api-stub-generator/apistub/_metadata_map.py
  packages/python-packages/api-stub-generator/apistub/_stub_generator.py
  packages/python-packages/api-stub-generator/apistub/_token.py
  packages/python-packages/api-stub-generator/apistub/nodes/_argtype.py
  packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
  packages/python-packages/api-stub-generator/apistubgen.py
  packages/python-packages/api-stub-generator/tests/apiview_test.py
  packages/python-packages/apistubgentest/apiview_mapping.json
Labels: APIView, Python

#2830 Improve Cosmos Emulator logic
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
Labels: Central-EngSys, Do Not Merge

#2849 Update to github-codeowner-subscriber version and use env variable
  eng/pipelines/notifications.yml
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys

#2824 The common scripts of PR git diff changes.
  eng/common/scripts/git-diff-changes.ps1
Labels: auto-merge

#2860 [Test Proxy] Misspelling correction
  tools/test-proxy/README.md
Labels: Docs, Central-EngSys

#2798 [Python APIView] Fix ItemPaged/AsyncItemPaged warning and Required kwargs
  .azure-pipelines/apiview.yml
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/_stub_generator.py
  packages/python-packages/api-stub-generator/apistub/_version.py
  packages/python-packages/api-stub-generator/apistub/nodes/_argtype.py
  packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
  packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_variable_node.py
  packages/python-packages/api-stub-generator/tests/class_parsing_test.py
  packages/python-packages/api-stub-generator/tests/docstring_parser_test.py
  packages/python-packages/api-stub-generator/tests/function_parsing_test.py
  packages/python-packages/apistubgentest/apistubgentest/models/__init__.py
  packages/python-packages/apistubgentest/apistubgentest/models/_models.py
Labels: APIView, Python

#2875 Support staging URl to run detect API changes in test env
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: auto-merge

#2880 [Python APIView] Fix alias display names and enum values
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/apistub/_apiview.py
  packages/python-packages/api-stub-generator/apistub/_node_index.py
  packages/python-packages/api-stub-generator/apistub/_stub_generator.py
  packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_enum_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
  packages/python-packages/api-stub-generator/tests/apiview_test.py
  packages/python-packages/api-stub-generator/tests/class_parsing_test.py
  packages/python-packages/apistubgentest/apistubgentest/models/__init__.py
  packages/python-packages/apistubgentest/apistubgentest/models/_models.py
Labels: APIView, Python

#2810 Add AZURE_SERVICE_DIRECTORY environment variable in test deployment script
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: auto-merge, Central-EngSys

#2889 Support local test resources behavior with provisioner config
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#2892 Support namespace override for local stress test deployments
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/chaos/README.md
Labels: auto-merge, Central-EngSys, Stress

#2836 Verify ChangeLog as ForRelease
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: auto-merge, Central-EngSys

#2904 [Python APIView] Add more enum tests and tests for Metaclasses
  packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
  packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
  packages/python-packages/apistubgentest/apistubgentest/models/__init__.py
  packages/python-packages/apistubgentest/apistubgentest/models/_models.py
  packages/python-packages/apistubgentest/requirements.txt
  packages/python-packages/apistubgentest/setup.py
Labels: APIView, Python

#2909 Updates to codesnippet-maven-plugin
  packages/java-packages/codesnippet-maven-plugin/pom.xml
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetReplacement.java
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
Labels: Java

#2912 Adds Benchmarks to codesnippet-maven-plugin
  packages/java-packages/codesnippet-maven-plugin/pom.xml
  packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetReplacement.java
  packages/java-packages/codesnippet-maven-plugin/src/test/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetReplacementBenchmark.java
Labels: Java

#2902 Update to public interface of partner release pipelines
  eng/pipelines/azuresdkpartnerdrops-to-devops.yml
  eng/pipelines/azuresdkpartnerdrops-to-nuget.yml
Labels: Central-EngSys

#2910 Read the ms.service value from csv metadata
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#2913 [Matrix-Generation] Support additional customized steps before matrix generation
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/README.md
Labels: Central-EngSys

#2870 Skip component governance in generate matrix job
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: auto-merge, Central-EngSys

#2866 Set owners tag in test resource deployments
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#2901 [Credscan] Compliance w/out changed files shouldn't crash
  eng/common/pipelines/templates/steps/credscan.yml
Labels: Central-EngSys

#2922 Fix toc which need to add group id property
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: auto-merge

#2936 Add github alias rules to resource management guidelines
  doc/engsys_resource_management.md
Labels: Central-EngSys

#2847 Merge test resource cleanup scripts. Support owner tags, CI and interactive modes.
  doc/engsys_resource_management.md
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/pipelines/live-test-cleanup-template.yml
  eng/pipelines/live-test-cleanup.yml
  eng/scripts/cleanup-allowlist.txt
  eng/scripts/live-test-resource-cleanup.ps1
  scripts/powershell/sub-cleanup/sub-cleanup.ps1
Labels: auto-merge, Central-EngSys

#2928 Fixed the place having duplicates
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: auto-merge

#2953 Add k8s namespace to stress test resource group name
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
Labels: Central-EngSys, Stress

#2939 Fixed not filter out group id issue.
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: auto-merge, Central-EngSys

#2938 Add support for service names containing a forward slash
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: auto-merge

#2861 Use common script for git diff changes.
  eng/common/pipelines/templates/steps/credscan.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Detect-Api-Changes.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/get-changedfiles.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
  eng/common/scripts/git-diff-changes.ps1
Labels: auto-merge, Central-EngSys

#2972 Fix the target branch setting and validation
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Helpers/git-helpers.ps1
Labels: auto-merge, Central-EngSys

#2893 Add navigation buttons to next and previous comments
  src/dotnet/APIView/APIViewWeb/Client/css/site.scss
  src/dotnet/APIView/APIViewWeb/Client/src/comments.ts
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
Labels: Central-EngSys

#2983 Improved C++ Language Service handling of templates and ServiceVersion constants
  src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
Labels: C++

#2990 Send link to generated API review to PR pipeline caller
  src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
  src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
Labels: APIView

#2979 clean up cspell target and source branch, use default one in git-helper
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: auto-merge, Central-EngSys

#3017 Apiview recursive java fix
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/MiscUtils.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MavenPackageAndDescriptionDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Pom.java
Labels: APIView
