Repository Azure/azure-sdk-tools, pull requests merged in 2022-07, with the labels that each got.

#3563 Enable verify-samples to handle multiple service directories
  eng/common/pipelines/templates/steps/verify-samples.yml
Labels: EngSys, auto-merge

#3428 Update mgmt toc structure
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: auto-merge

#3527 Only update/override powershell module path when in CI on module script import
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  tools/stress-cluster/chaos/README.md
Labels: auto-merge, Central-EngSys

#3500 [Test-Proxy] Test Version With Transport customizations enabled
  eng/common/testproxy/target_version.txt
Labels: auto-merge

#3480 Do not allow check in the files only differ in case
  eng/common/pipelines/templates/steps/validate-filename.yml
Labels: auto-merge

#3544 Integration Tests
  .azure-pipelines/apiview.yml
  src/dotnet/APIView/APIView.sln
  src/dotnet/APIView/APIViewIntegrationTests/APIViewIntegrationTests.csproj
  src/dotnet/APIView/APIViewIntegrationTests/CosmosReviewRepositoryTests.cs
  src/dotnet/APIView/APIViewTest/APIViewUnitTests.csproj
  src/dotnet/APIView/APIViewTest/CodeFileBuilderTests.cs
  src/dotnet/APIView/APIViewTest/DiagnosticProject.cs
  src/dotnet/APIView/APIViewTest/DiffTests.cs
  src/dotnet/APIView/APIViewWeb/Client/babel.config.js
  src/dotnet/APIView/APIViewWeb/Client/package.json
  src/dotnet/APIView/APIViewWeb/Client/src/shims-tsx.d.ts
  src/dotnet/APIView/APIViewWeb/Client/src/shims-vue.d.ts
  src/dotnet/APIView/APIViewWeb/Client/tsconfig.json
  src/dotnet/APIView/APIViewWeb/Client/webpack.config.js
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
  src/dotnet/APIView/APIViewWeb/Properties/launchSettings.json
  src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
  src/dotnet/APIView/APIViewWeb/wwwroot/reviews.js.map
Labels: Central-EngSys

#3546 Fix null errors in SetTestPipelineVersion
  eng/common/scripts/SetTestPipelineVersion.ps1
  eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
Labels: auto-merge

#3590 Update set-test-pipeline-version logic to handle one or more packages
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: auto-merge

#3606 Use --no-cone in pipeline sparse checkout script
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: auto-merge, Central-EngSys

#3578 Have language specific download link.
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge

#3634 Skip updating line ID when rendering review file
  src/dotnet/APIView/APIView/CodeFileRenderer.cs
  src/dotnet/APIView/APIViewTest/CodeFileRendererTests.cs
Labels: APIView, auto-merge, Central-EngSys

#3649 Switch example access stress cluster name
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys, Stress

#3657 [Perf] Move perf.yml to eng/common
  eng/common/pipelines/templates/jobs/perf.yml
Labels: auto-merge

#3656 [Test-Proxy] Allow eng/common/testproxy to be used via external reference
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge

#3628 Update casing for 'verison'
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#3700 [Perf] Print additional output formats
  eng/common/pipelines/templates/jobs/perf.yml
Labels: auto-merge

#3702 Add language-service to list of valid sample slugs
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: auto-merge

#3723 Update python version to 0.3.2
  src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Labels: APIView, Central-EngSys

#3661 Add full clone fallback to sparse checkout
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys

#3735 Detect API changes using pre-generated code file by CI approach
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: APIView, auto-merge

#3754 Revert "Add full clone fallback to sparse checkout"
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: auto-merge

#3347 Sandboxing changes: create apireview gen pipeline
  eng/pipelines/apiview-review-gen-python.yml
  eng/pipelines/templates/steps/apiview-review-gen.yml
  eng/scripts/Create-Apiview-Token-Files.ps1
  eng/scripts/Create-Apiview-Token-Python.ps1
Labels: Central-EngSys

#3753 Bump MacOs version to macos-11
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
Labels: auto-merge

#3757 APIVIew - Make GitHub token optional
  src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
Labels: APIView

#3775 Update sandboxing pipeline to send request to APIView
  eng/pipelines/templates/steps/apiview-review-gen.yml
  eng/scripts/Apiview-Update-Generated-Review.ps1
Labels: APIView, Central-EngSys

#3778 Return 401 error code if org info is not available for PR owner
  src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
Labels: APIView, Central-EngSys

#3787 Fix misleading step name in az module install
  eng/common/TestResources/setup-environments.yml
Labels: auto-merge, Central-EngSys
