Repository Azure/azure-sdk-tools, pull requests merged in 2022-05, with the labels that each got.

#3261 Short circuit msdocs publish if no package locations are specified
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Labels: auto-merge

#3269 Update the get-codeowner tool to the latest
  eng/common/scripts/get-codeowners.ps1
Labels: auto-merge

#3280 Update pipeline-generator version
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: auto-merge

#3217 Add diagnostics to Go API reviews
  src/go/cmd/api_view.go
  src/go/cmd/api_view_test.go
  src/go/cmd/content.go
  src/go/cmd/models.go
  src/go/cmd/module.go
  src/go/cmd/pkg.go
  src/go/cmd/testdata/test_diagnostics/go.mod
  src/go/cmd/testdata/test_diagnostics/internal/internal.go
  src/go/cmd/testdata/test_diagnostics/test.go
  src/go/cmd/testdata/test_subpackage/go.mod
  src/go/cmd/testdata/test_subpackage/subpackage/test.go
  src/go/cmd/testdata/test_subpackage/test.go
  src/go/cmd/token_builders.go
  src/go/cmd/token_makers.go
Labels: APIView, Go

#3264 Handle startup exceptions and add it to telemetry
  src/dotnet/APIView/APIViewWeb/HostedServices/PullRequestBackgroundHostedService.cs
  src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: Central-EngSys

#3305 [stress testing] Add docs for custom docker build commands
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys, Stress

#3170 Asset Relocation Script Prototype
  .gitignore
  eng/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  tools/asset-sync/README.md
  tools/asset-sync/assets.Tests.Helpers.ps1
  tools/asset-sync/assets.Tests.ps1
  tools/asset-sync/assets.json
  tools/asset-sync/assets.ps1
  tools/asset-sync/ci.yml
  tools/asset-sync/contributing.md
Labels: Central-EngSys

#3262 Fix Issues of CodeLines Hiding Under the Navigation Bar
  src/dotnet/APIView/APIViewWeb/Client/css/site.scss
Labels: EngSys, Central-EngSys

#3320 Update readme for -pre and -post TestResource scripts
  eng/common/TestResources/README.md
Labels: auto-merge

#3323 [testresources] String parsing improvements to service directory resource names
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: auto-merge, Central-EngSys

#3335 [Python APIView] Move pylintrc into the apistub folder and include in the WHL
  packages/python-packages/api-stub-generator/CHANGELOG.md
  packages/python-packages/api-stub-generator/MANIFEST.in
  packages/python-packages/api-stub-generator/apistub/_apiview.py
  packages/python-packages/api-stub-generator/apistub/_version.py
  packages/python-packages/api-stub-generator/apistub/pylintrc
  packages/python-packages/api-stub-generator/setup.py
Labels: bug, APIView

#3341 Add skip variable for remove test resources to support debugging
  eng/common/TestResources/remove-test-resources.yml
Labels: auto-merge, Central-EngSys

#3304 Create consolidated APIView comment
  src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
  src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
Labels: Central-EngSys

#3189 When installing dev package, target a specific index
  packages/python-packages/api-stub-generator/apiview_reqs.txt
  packages/python-packages/api-stub-generator/setup.py
  packages/python-packages/api-stub-generator/tox.ini
Labels: Central-EngSys

#3287 Add github action based check enforcer
  .github/workflows/event.yaml
Labels: Central-EngSys

#3342 Delete PR and branch which central PR is closed
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/pipelines/branch-cleanup.yml
  eng/pipelines/eng-common-sync.yml
Labels: auto-merge

#3357 Remove invalid arg to python api stub gen
  src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Repositories/PackageNameManager.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Labels: Central-EngSys

#3362 Spell-check skippable by variable
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: auto-merge, Central-EngSys

#3363 [Test-Proxy] Support Extensible Storage
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TransformTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/AssetsConfiguration.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitAssetsConfiguration.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/IAssetsStore.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/NullStore.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/StoreResolver.cs
Labels: Central-EngSys, Asset-Sync, Test-Proxy

#3364 Bug fix/cg issues
  tools/mock-service-host/npm-shrinkwrap.json
  tools/mock-service-host/package.json
  tools/sdk-generation-pipeline/common/config/rush/pnpm-lock.yaml
  tools/sdk-generation-pipeline/packages/sdk-generation-cli/package.json
  tools/sdk-generation-pipeline/packages/sdk-generation-lib/package.json
Labels: EngSys, Central-EngSys

#3377 Use yml extension in github workflow for consistency
  .github/workflows/event.yml
Labels: Central-EngSys

#3380 update doc
  tools/sdk-generation-pipeline/packages/sdk-generation-cli/README.md
Labels: SDK Generation Pipeline

#3382 Simple readme update test
  tools/stress-cluster/cluster/README.md
Labels: auto-merge, Central-EngSys

#3378 Create json package property parent directory
  eng/common/scripts/Save-Package-Properties.ps1
Labels: auto-merge
