Repository Azure/azure-sdk-tools, pull requests merged in 2023-08, with the labels that each got.

#6786 Copilot comments search
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Controllers/CopilotCommentsController.cs
  src/dotnet/APIView/APIViewWeb/Managers/CopilotCommentsManager.cs
  src/dotnet/APIView/APIViewWeb/Managers/ICopilotCommentsManager.cs
  src/dotnet/APIView/APIViewWeb/Models/CopilotCommentModel.cs
  src/dotnet/APIView/APIViewWeb/Models/CopilotSearchModel.cs
  src/dotnet/APIView/APIViewWeb/Repositories/CopilotCommentsRepository.cs
  src/dotnet/APIView/APIViewWeb/Repositories/ICopilotCommentsRepository.cs
Labels: APIView, Central-EngSys, Intern

#6854 Strong name sign Sodium.Core in secret library
  tools/secret-management/Azure.Sdk.Tools.AccessManagement/Azure.Sdk.Tools.AccessManagement.csproj
  tools/secret-management/Directory.Build.props
Labels: Central-EngSys

#6849 Update the team/user store to store additional information to be used in the upcoming CODEOWNERS linter
  eng/pipelines/pipeline-owners-extraction.yml
  tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/Constants/ProductAndTeamConstants.cs
  tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/GitHubEventClient.cs
  tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/Program.cs
  tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/RepositoryLabelGenerator.cs
  tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/TeamUserGenerator.cs
Labels: CODEOWNERS Linter

#6857 Revert "Strong name sign Sodium.Core in secret library"
  tools/secret-management/Azure.Sdk.Tools.AccessManagement/Azure.Sdk.Tools.AccessManagement.csproj
  tools/secret-management/Directory.Build.props
Labels: Central-EngSys

#6853 Fail fast on variable conflicts with subscription config
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/build-test-resource-config.yml
Labels: Central-EngSys

#6858 Skip strong name signing validation for secret cli
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  tools/secret-management/ci.yml
Labels: Central-EngSys

#6879 Bump stress cluster version to 1.26.6
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
Labels: Central-EngSys, Stress

#6890 [stress] Use dotnet mariner for stress watcher
  tools/stress-cluster/services/Stress.Watcher/Dockerfile
Labels: Central-EngSys, Stress
