Repository Azure/azure-sdk-tools, pull requests merged in 2023-10, with the labels that each got.

#7039 Use AzureLinux for stress cluster nodes
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
Labels: Central-EngSys, Stress

#7071 [JimBot] Update package version in use
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
  tools/github-event-processor/YmlAndConfigFiles/event-processor.yml
  tools/github-event-processor/YmlAndConfigFiles/scheduled-event-processor.yml
Labels: GitHub Event Processor

#7092 Remove CXPAttention rules constant
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Constants/RulesConstants.cs
Labels: GitHub Event Processor

#7098 Update github-event-processor version to 1.0.0-dev.20231010.2
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: GitHub Event Processor

#7075 Set product as parent of package work item.
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: Central-EngSys

#7113 Remove ARM deployment in test resources
  eng/common/TestResources/New-TestResources.ps1
  eng/scripts/Remove-WormStorageAccounts.ps1
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#7171 Fix update test resources tagging when tags are empty. Bump max limit
  eng/common/TestResources/Update-TestResources.ps1
Labels: Central-EngSys

#7160 Add max lifespan parameter to resource groups
  doc/engsys_resource_management.md
  eng/pipelines/live-test-cleanup.yml
  eng/scripts/Remove-WormStorageAccounts.ps1
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#7179 Minor fixes on arm deployment cleanup
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#7178 Update tools versions for CodeownersUtils
  eng/pipelines/templates/variables/globals.yml
Labels: CODEOWNERS Parser

#7185 Check az login for target subscription in stress deploy login
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: Central-EngSys

#7183 Clean up arm deployments with secret parameters
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#7186 Temporarily disable ACS dogfood cleanup
  eng/pipelines/live-test-cleanup.yml
Labels: Central-EngSys

#7192 Add storage account immutability cleanup to live test resources script
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#7197 Fix invocation of remove worm script
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#7210 Reduce APIView search query cost when searching without filters
  src/dotnet/APIView/APIView/APIView.csproj
  src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
Labels: APIView, Central-EngSys

#7212 Show enum members in JS API review
  src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
  tools/apiview/parsers/js-api-parser/export.ts
  tools/apiview/parsers/js-api-parser/package.json
Labels: APIView, Central-EngSys

#7214 Update Chrome driver to latest for APIView UI test
  src/dotnet/APIView/APIViewUITests/APIViewUITests.csproj
Labels: APIView, Central-EngSys
