Repository Azure/azure-sdk-tools, pull requests merged in 2023-01, with the labels that each got.

#5007 Improve diagnostic output + refactor handling of packages-to-be-published directory in `archetype-sdk-tool-dotnet.yml`
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/steps/produce-net-standalone-packs.yml
Labels: Central-EngSys

#4996 Update Ubuntu images to 1ES-hosted Ubuntu 22.04 in many places
  .azure-pipelines/warden.yml
  eng/containers/ci.yml
  eng/pipelines/apiview-review-gen-cadl.yml
  eng/pipelines/apiview-review-gen-javascript.yml
  eng/pipelines/apiview-review-gen-python.yml
  eng/pipelines/eng-common-sync.yml
  eng/pipelines/githubio-linkcheck.yml
  eng/pipelines/live-test-cleanup.yml
  eng/pipelines/merge-docs-main-to-live.yml
  eng/pipelines/mirror-pypi-to-dev-feed.yml
  eng/pipelines/mirror-repos.yml
  eng/pipelines/notifications.yml
  eng/pipelines/pipeline-generation-single.yml
  eng/pipelines/pipeline-generation.yml
  eng/pipelines/pipeline-owners-extraction.yml
  eng/pipelines/publish-docker-image.yml
  eng/pipelines/templates/jobs/stress-cluster-provision.yml
  eng/pipelines/templates/jobs/stress-test-release.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-function.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-webapp.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
  eng/pipelines/tools-repo-versioning.yml
  packages/java-packages/codesnippet-maven-plugin/ci.yml
  scripts/python/util/install_python_version.py
  tools/apiview/emitters/cadl-apiview/ci.yml
  tools/apiview/parsers/js-api-parser/ci.yml
  tools/oav-traffic-converter/ci.yml
  tools/perf-automation/tests.yml
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/ci.yml
  tools/stress-cluster/cluster/README.md
  tools/test-proxy/ci.yml
  tools/test-proxy/tests.yml
Labels: Central-EngSys

#5005 Update Ubuntu images in `eng/common` to Ubuntu 22.04
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/jobs/perf.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: auto-merge, Central-EngSys

#5050 Resolve Paths within Linux Executable
  eng/pipelines/templates/steps/produce-net-standalone-packs.yml
Labels: Test-Proxy

#5042 Delete GHCreator and its usages
  tools/github-labels/.gitignore
  tools/github-labels/README.md
  tools/github-labels/deploy-labels.ps1
  tools/github-labels/diff-repo-labels.ps1
  tools/github-labels/ghcreator/CommandLine.dll
  tools/github-labels/ghcreator/ComposableAsync.Core.dll
  tools/github-labels/ghcreator/CsvHelper.dll
  tools/github-labels/ghcreator/GHCreator.deps.json
  tools/github-labels/ghcreator/GHCreator.dll
  tools/github-labels/ghcreator/GHCreator.runtimeconfig.dev.json
  tools/github-labels/ghcreator/GHCreator.runtimeconfig.json
  tools/github-labels/ghcreator/Octokit.dll
  tools/github-labels/ghcreator/OutputColorizer.dll
  tools/github-labels/ghcreator/RateLimiter.dll
  tools/github-labels/refresh-snapshots.ps1
  tools/github-labels/scan-new-labels.ps1
Labels: Central-EngSys

#5027 Move supporting matrix generator assets out of `eng/common`
  doc/common/matrix_generator.md
  eng/common-tests/matrix-generator/samples/matrix-job-sample.yml
  eng/common-tests/matrix-generator/samples/matrix-test.yml
  eng/common-tests/matrix-generator/samples/matrix.json
  eng/common-tests/matrix-generator/tests/job-matrix-functions.filter.tests.ps1
  eng/common-tests/matrix-generator/tests/job-matrix-functions.modification.tests.ps1
  eng/common-tests/matrix-generator/tests/job-matrix-functions.tests.ps1
  eng/common-tests/matrix-generator/tests/test-import-matrix.json
  eng/common/scripts/job-matrix/README.md
Labels: auto-merge, Central-EngSys

#5044 Add `global.json` and other missing paths to `CODEOWNERS`
  .github/CODEOWNERS
Labels: Central-EngSys

#5023 Update `doc/common/matrix_generator.md`: review and rewrite for clarity
  doc/common/matrix_generator.md
Labels: Docs, Central-EngSys

#5054 Revert "Migrate eng/common to Ubuntu 22.04" for perf.yml
  eng/common/pipelines/templates/jobs/perf.yml
Labels: auto-merge

#5003 Update perf-automation to `net6.0`; get rid of remaining, now no-op, overrides of `DotNetCoreVersion`
  tools/perf-automation/ci.yml
  tools/pipeline-owners-extractor/ci.yml
  tools/stress-cluster/services/Stress.Watcher/ci.yml
  tools/test-proxy/ci.yml
Labels: Central-EngSys

#5052 Minor message fix in `archetype-sdk-tool-dotnet.yml`: XOR to or
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
Labels: Central-EngSys

#5059 Hyperlink from eng/common job-matrix README to matrix_generator.md
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, auto-merge, Central-EngSys

#5063 Replace the glob-based CODEOWNERS parser with regex-based
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeOwnersFileTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
  tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeOwnerEntry.cs
  tools/identity-resolution/identity-resolution.csproj
  tools/notification-configuration/notification-creator/Azure.Sdk.Tools.NotificationConfiguration.csproj
  tools/notification-configuration/notification-creator/Program.cs
Labels: Central-EngSys

#5043 Update `global.json` `Microsoft.Build.Traversal` from `1.0.45` to `3.2.0`
  global.json
Labels: Central-EngSys

#5085 Update versions of packages `RetrieveCodeOwners`, `NotificationConfiguration` and `PipelineOwnersExtractor` to most recent as of 1/8/2023
  eng/common/scripts/get-codeowners.ps1
  eng/pipelines/templates/variables/globals.yml
Labels: auto-merge, Central-EngSys

#5095 Fix broken relative paths in `matrix-generator` tests and samples + make the tests runnable by `common-tests/ci.yml`.
  eng/common-tests/matrix-generator/samples/matrix-test.yml
  eng/common-tests/matrix-generator/tests/job-matrix-functions.filter.tests.ps1
  eng/common-tests/matrix-generator/tests/job-matrix-functions.modification.tests.ps1
  eng/common-tests/matrix-generator/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: auto-merge, Central-EngSys

#5006 Update `ubuntu-latest` images: set them to Ubuntu 22.04 XOR comment they are `latest` intentionally
  .github/workflows/event.yml
  .github/workflows/label-to-project.yml
  eng/pipelines/setup-tutorial-branch.yml
  tools/js-sdk-release-tools/ci.yml
  tools/mock-service-host/ci.yml
  tools/sdk-testgen/ci.yml
Labels: Central-EngSys

#5045 Migrate all usages of `task: UseDotNet@2` to template `install-net.yml`
  .azure-pipelines/apiview.yml
  eng/pipelines/apiview-review-gen-swagger.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-function.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-webapp.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/steps/install-dotnet.yml
  eng/pipelines/templates/variables/globals.yml
  src/dotnet/Mgmt.CI.BuildTools/ci.yml
  tools/test-proxy/tests.yml
Labels: Central-EngSys

#5090 Add regex-based CODEOWNERS matcher tests for "/" and file names with spaces.
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeOwnersFileTests.cs
Labels: Central-EngSys

#5104 Make improvements to `retrieve-codeowners` tool: change accepted params (`targetPath` etc.) + refactor
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeownersFileTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ConsoleOutput.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/MainTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ProgramTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
  tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs
  tools/code-owners-parser/CodeOwnersParser/CodeownersEntry.cs
  tools/code-owners-parser/CodeOwnersParser/CodeownersFile.cs
  tools/code-owners-parser/CodeOwnersParser/FileHelpers.cs
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
  tools/identity-resolution/Services/GitHubService.cs
  tools/notification-configuration/notification-configuration.sln.DotSettings
  tools/notification-configuration/notification-creator/NotificationConfigurator.cs
  tools/notification-configuration/notification-creator/YamlHelper.cs
Labels: Central-EngSys

#5123 Set Package name for GO API reviews
  src/go/cmd/module.go
Labels: Central-EngSys

#5121 Fix Github to GitHub
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
Labels: auto-merge

#5048 Revert `Azure.ClientSdk.Analyzers` library to target `netstandard2.0` instead of `net6.0`.
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
Labels: Central-EngSys

#5113 Update on existing metadata json file.
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: auto-merge

#5134 Add to the `retrieve-codeowners` tool support for returning owners for all paths matching given glob path.
  eng/common/scripts/get-codeowners.ps1
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeownersFileTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/Azure.Sdk.Tools.RetrieveCodeOwners.Tests.csproj
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ConsoleOutput.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ProgramGlobPathTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ProgramSimplePathTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/a.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/b.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/foo/a.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/foo/b.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/foo/bar/a.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/foo/bar/b.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/glob_path_CODEOWNERS
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/simple_path_CODEOWNERS
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Azure.Sdk.Tools.RetrieveCodeOwners.csproj
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
  tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj
  tools/code-owners-parser/CodeOwnersParser/CodeownersEntry.cs
  tools/code-owners-parser/CodeOwnersParser/CodeownersFile.cs
  tools/code-owners-parser/CodeOwnersParser/GlobFilePath.cs
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
  tools/code-owners-parser/CodeOwnersParser/PathExtensions.cs
Labels: auto-merge, Central-EngSys

#4959 Add script for removing worm storage accounts
  eng/scripts/Remove-WormStorageAccounts.ps1
Labels: Central-EngSys

#5164 fix failing test-proxy livetests -- the run-pester-tests template was renamed
  tools/test-proxy/tests.yml
Labels: Central-EngSys

#5172 `notification-configuration`: write out repo URL used to obtain CODEOWNERS file
  tools/notification-configuration/notification-creator/NotificationConfigurator.cs
Labels: Central-EngSys

#5177 Update ` Azure.Sdk.Tools.NotificationConfiguration` in `globals.yml` from `20230108.1` to `20230119.1`
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys

#5165 Implement tools for diffing sets of owners of repo paths; update the regex-based CODEOWNERS matching logic
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeownersFileTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CodeownersDiffTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ProgramGlobPathTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/glob_path_CODEOWNERS
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
  tools/code-owners-parser/CodeOwnersParser.sln.DotSettings
  tools/code-owners-parser/CodeOwnersParser/CodeownersFile.cs
  tools/code-owners-parser/CodeOwnersParser/GlobFilePath.cs
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
Labels: Central-EngSys

#5187 Remove CHECKENFORCER file
  eng/CHECKENFORCER
Labels: Central-EngSys

#5175 Unhardcode C# lang versions, making them use TFM default (currently `10.0` due to TFM of `net6.0`).
  eng/Directory.Build.props
  src/dotnet/APIView/APIView/APIView.csproj
  src/dotnet/APIView/APIViewIntegrationTests/APIViewIntegrationTests.csproj
  src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
  src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
  tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj
  tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/SwaggerApiParserTest.csproj
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/Azure.Sdk.Tools.CodeOwnersParser.Tests.csproj
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/Azure.Sdk.Tools.RetrieveCodeOwners.Tests.csproj
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Azure.Sdk.Tools.RetrieveCodeOwners.csproj
  tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Azure.Sdk.Tools.PipelineWitness.csproj
  tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/Azure.Sdk.Tools.SnippetGenerator.Tests.csproj
  tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/Azure.Sdk.Tools.SnippetGenerator.csproj
Labels: Central-EngSys

#5169 Handle service principal creation quota errors
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#4963 Delete obsolete CheckEnforcer tool
  README.md
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer.Tests/Azure.Sdk.Tools.CheckEnforcer.Tests.csproj
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer.Tests/Integrations/GitHub/GitHubWebhookSignatureValidatorTest.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/CheckEnforcerException.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/CheckEnforcerSecurityException.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/CheckEnforcerConfigurationException.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/GlobalConfigurationProvider.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IGlobalConfigurationProvider.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IRepositoryConfiguration.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IRepositoryConfigurationProvider.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfiguration.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfigurationProvider.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Constants.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverEventHubsFunction.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/PingFunction.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/PullRequestTimeoutFunction.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckRunHandler.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/HandlerContext.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubClientProvider.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubRateLimiter.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubWebhookSignatureValidator.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/IGitHubClientProvider.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/IPullRequestTracker.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/PullRequestTracker.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/PullRequestTrackingTicket.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Startup.cs
  tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/host.json
  tools/check-enforcer/CheckEnforcer.sln
  tools/check-enforcer/README.md
  tools/check-enforcer/ci.yml
Labels: Central-EngSys

#5214 Extract `Contacts` class + related refactorings to `NotificationConfigurator` class.
  tools/identity-resolution/Services/GitHubService.cs
  tools/notification-configuration/notification-creator/Contacts.cs
  tools/notification-configuration/notification-creator/NotificationConfigurator.cs
Labels: Central-EngSys

#5218 test-proxy always logs exceptions on console
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
Labels: Central-EngSys

#5244 Move APIView pipelines to APIView directory
  src/dotnet/APIView/apiview-sync-staging.yml
  src/dotnet/APIView/apiview.yml
Labels: auto-merge, Central-EngSys

#5224 Add Template for Upload of Proxy Logs
  eng/common/testproxy/publish-proxy-logs.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge, Central-EngSys

#5242 [test resources] Consolidate naming logic and generate short hash names for local use
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: auto-merge, Central-EngSys

#5241 Enable regex-based wildcard-supporting CODEOWNERS matcher for `azure-sdk-for-net` repo
  tools/notification-configuration/notification-creator/Contacts.cs
Labels: Central-EngSys

#5245 Add detection of `CODEOWNERS` paths that are missing suffix slash; add support for diffing to `CODEOWNERS` version with some paths removed; add tools for analyzing azure-sdk-for-python `CODEOWNERS`.
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CodeownersManualAnalysisTests.cs
  tools/code-owners-parser/CodeOwnersParser/CodeownersFile.cs
Labels: Central-EngSys

#5247 Add `Azure.Sdk.Tools.NotificationConfiguration.Tests` + improve `NotificationConfiguration.Program.Main`
  tools/notification-configuration/notification-configuration.sln
  tools/notification-configuration/notification-creator.Tests/Azure.Sdk.Tools.NotificationConfiguration.Tests.csproj
  tools/notification-configuration/notification-creator.Tests/ProgramTests.cs
  tools/notification-configuration/notification-creator/Program.cs
Labels: Central-EngSys

#5240 Update `NotificationConfiguration` package from `20230119.1` to `20230127.4`
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys

#5231 Move cadl project scripts to common
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
  eng/common/scripts/common.ps1
Labels: auto-merge

#5259 Repair failing test-proxy livetests
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
Labels: Test-Proxy

#5294 Update Swagger parser version used for manual API review gen
  eng/pipelines/apiview-review-gen-swagger.yml
Labels: Central-EngSys

#5272 Add documentation for cadl sync and generate
  doc/common/Cadl-Project-Scripts.md
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: auto-merge

#5278 Update JS api parser dependency
  src/dotnet/APIView/apiview.yml
  tools/apiview/parsers/js-api-parser/ci.yml
  tools/apiview/parsers/js-api-parser/package.json
Labels: APIView, Central-EngSys
