Repository Azure/azure-sdk-tools, pull requests merged in 2023-04, with the labels that each got.

#5899 Rename `api-stub-generator` to `apiview-stub-generator`
  eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
  eng/scripts/python_sdk_report.py
  eng/scripts/python_version_check.py
  packages/python-packages/apiview-stub-generator/CHANGELOG.md
  packages/python-packages/apiview-stub-generator/MANIFEST.in
  packages/python-packages/apiview-stub-generator/README.md
  packages/python-packages/apiview-stub-generator/apistub/__init__.py
  packages/python-packages/apiview-stub-generator/apistub/__main__.py
  packages/python-packages/apiview-stub-generator/apistub/_apiview.py
  packages/python-packages/apiview-stub-generator/apistub/_diagnostic.py
  packages/python-packages/apiview-stub-generator/apistub/_metadata_map.py
  packages/python-packages/apiview-stub-generator/apistub/_node_index.py
  packages/python-packages/apiview-stub-generator/apistub/_stub_generator.py
  packages/python-packages/apiview-stub-generator/apistub/_token.py
  packages/python-packages/apiview-stub-generator/apistub/_token_kind.py
  packages/python-packages/apiview-stub-generator/apistub/_version.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/__init__.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_annotation_parser.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_argtype.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_astroid_parser.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_base_node.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_class_node.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_data_class_node.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_docstring_parser.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_enum_node.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_function_node.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_key_node.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_module_node.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_property_node.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_pylint_parser.py
  packages/python-packages/apiview-stub-generator/apistub/nodes/_variable_node.py
  packages/python-packages/apiview-stub-generator/apistub/pylintrc
  packages/python-packages/apiview-stub-generator/apistubgen.py
  packages/python-packages/apiview-stub-generator/apiview_reqs.txt
  packages/python-packages/apiview-stub-generator/ci.yml
  packages/python-packages/apiview-stub-generator/dev_requirements.txt
  packages/python-packages/apiview-stub-generator/setup.py
  packages/python-packages/apiview-stub-generator/tests/__init__.py
  packages/python-packages/apiview-stub-generator/tests/_test_util.py
  packages/python-packages/apiview-stub-generator/tests/apiview_test.py
  packages/python-packages/apiview-stub-generator/tests/class_parsing_test.py
  packages/python-packages/apiview-stub-generator/tests/dataclass_parsing_test.py
  packages/python-packages/apiview-stub-generator/tests/docstring_parser_test.py
  packages/python-packages/apiview-stub-generator/tests/function_parsing_test.py
  packages/python-packages/apiview-stub-generator/tox.ini
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
Labels: Central-EngSys

#5918 Bump credscan to 2.3.12.23
  eng/common/pipelines/templates/steps/credscan.yml
Labels: auto-merge, Central-EngSys

#5924 [test resources] Fix regression - base name overrides in CI
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: auto-merge, Central-EngSys, Stress

#5935 Add diagnostic rules for ExpandableStringEnum
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ExpandableStringEnumDiagnosticRule.java
Labels: APIView, Java

#5951 Switch to using standard PAT tokens instead of base 64
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/logging.ps1
  eng/pipelines/templates/steps/sync-directory.yml
Labels: auto-merge

#5988 Update rule name and criteria
  tools/github-event-processor/RULES.md
Labels: GitHub Event Processor

#5748 Prevent duplicate tag push
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationResetTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
  tools/test-proxy/scripts/test-scripts/CLIIntegration.Tests.ps1
  tools/test-proxy/scripts/test-scripts/assets.Tests.Helpers.ps1
Labels: Asset-Sync

#5991 Update Proxy Version
  eng/common/testproxy/target_version.txt
Labels: auto-merge, Central-EngSys

#5995 update sparse checkout path every time
  eng/common/scripts/TypeSpec-Project-Sync.ps1
Labels: auto-merge

#6004 Update Ubuntu `18.04` to `2X.04` ; update `MMSUbuntu2X.04` to `ubuntu-2X.04`
  doc/common/matrix_generator.md
  eng/common-tests/matrix-generator/samples/matrix-test.yml
  eng/common-tests/matrix-generator/samples/matrix.json
  eng/common-tests/matrix-generator/tests/job-matrix-functions.filter.tests.ps1
  eng/common-tests/matrix-generator/tests/job-matrix-functions.modification.tests.ps1
  eng/common-tests/matrix-generator/tests/job-matrix-functions.tests.ps1
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/containers/ci.yml
  eng/pipelines/apiview-review-gen-cadl.yml
  eng/pipelines/apiview-review-gen-javascript.yml
  eng/pipelines/apiview-review-gen-python.yml
  eng/pipelines/apiview-review-gen-typespec.yml
  eng/pipelines/doc-warden.yml
  eng/pipelines/eng-common-sync.yml
  eng/pipelines/git-tasks.yml
  eng/pipelines/githubio-linkcheck.yml
  eng/pipelines/live-test-cleanup.yml
  eng/pipelines/merge-docs-main-to-live.yml
  eng/pipelines/mirror-pypi-to-dev-feed.yml
  eng/pipelines/mirror-repos.yml
  eng/pipelines/notifications.yml
  eng/pipelines/pipeline-generation-single.yml
  eng/pipelines/pipeline-generation.yml
  eng/pipelines/pipeline-owners-extraction.yml
  eng/pipelines/publish-docker-image.yml
  eng/pipelines/setup-tutorial-branch.yml
  eng/pipelines/templates/jobs/stress-cluster-provision.yml
  eng/pipelines/templates/jobs/stress-test-release.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-function.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-azure-webapp.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
  eng/pipelines/tools-repo-versioning.yml
  tools/apiview/emitters/typespec-apiview/ci.yml
  tools/apiview/parsers/js-api-parser/ci.yml
  tools/oav-traffic-converter/ci.yml
  tools/sdk-generation-pipeline/build-publish-docker-image.yml
  tools/sdk-generation-pipeline/ci.yml
  tools/sdk-generation-pipeline/sdk-generation-pipeline.yml
  tools/stress-cluster/ci.yml
  tools/test-proxy/ci.yml
Labels: Central-EngSys

#5911 stress test error out for breaking helm versions
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: auto-merge, Central-EngSys, Stress

#6013 Update sdk-testgen vmImage to ubuntu-22.04
  tools/sdk-testgen/ci.yml
Labels: Central-EngSys

#6030 Have event processor get configs from raw githubusercontent instead of needing a sparse checkout
  tools/code-owners-parser/CodeOwnersParser/FileHelpers.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/MockGitHubEventClient.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Constants/ConfigConstants.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Program.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Utils/CodeOwnerUtils.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Utils/RulesConfiguration.cs
Labels: GitHub Event Processor

#6034 Create sync template for azure-sdk-tools
  eng/pipelines/eng-common-sync.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-repo-sync.yml
Labels: Central-EngSys

#6045 Script to verify that the json files used to generate docs have the required members.
  eng/common/scripts/Verify-RequiredDocsJsonMembers.ps1
Labels: Docs, auto-merge, Central-EngSys

#5898 Convert Inline Table Rows to Individual CodeLines
  eng/pipelines/templates/steps/apiview-ui-tests.yml
  src/dotnet/APIView/APIView/CodeFileRenderer.cs
  src/dotnet/APIView/APIView/Model/CodeFile.cs
  src/dotnet/APIView/APIViewIntegrationTests/APIViewIntegrationTests.csproj
  src/dotnet/APIView/APIViewIntegrationTests/ReviewManagerTests.cs
  src/dotnet/APIView/APIViewIntegrationTests/TestsBaseFixture.cs
  src/dotnet/APIView/APIViewUnitTests/CodeFileRendererTests.cs
  src/dotnet/APIView/APIViewUnitTests/ReviewManagerTests.cs.cs
  src/dotnet/APIView/APIViewWeb/Client/css/shared/codeline.scss
  src/dotnet/APIView/APIViewWeb/HostedServices/SwaggerReviewsBackgroundHostedService.cs
  src/dotnet/APIView/APIViewWeb/Managers/IReviewManager.cs
  src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
  src/dotnet/APIView/APIViewWeb/Startup.cs
  src/dotnet/APIView/apiview.yml
Labels: APIView, Central-EngSys

#6015 Enable event processor for azure-sdk-tools
  .github/event-processor.config
  .github/fabricbot.json
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: Central-EngSys, GitHub Event Processor
