Repository Azure/azure-sdk-tools, pull requests merged in 2023-02, with the labels that each got.

#4812 UI improvements/approve buttons
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
  eng/pipelines/templates/steps/apiview-ui-tests.yml
  src/dotnet/APIView/APIViewWeb/Client/tsconfig.json
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
  src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewBadge.cshtml
  tools/apiview/parsers/js-api-parser/package.json
Labels: auto-merge

#5292 Create API review for JS packages with namespace in api extractor model
  tools/apiview/parsers/js-api-parser/export.ts
  tools/apiview/parsers/js-api-parser/package.json
  tools/apiview/parsers/js-api-parser/tokensBuilder.ts
Labels: Central-EngSys

#5303 Pin dependencies used by api parser
  tools/apiview/parsers/js-api-parser/package.json
Labels: APIView, Central-EngSys

#5266 Add manual tools for reporting information required to enable regex-based wildcard-supporting `CODEOWNERS` matcher on all remaining repositories in scope.
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CodeownersManualAnalysisTests.cs
  tools/code-owners-parser/CodeOwnersParser.sln.DotSettings
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
  tools/notification-configuration/notification-configuration.sln.DotSettings
Labels: Central-EngSys

#5312 Update azure-sdk-build-tools Repository Resource Refs in Yaml files
  eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
  eng/pipelines/templates/scripts/assemble-dotnet-standalone-exe.ps1
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/steps/produce-net-standalone-packs.yml
  src/dotnet/Mgmt.CI.BuildTools/ci.yml
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
  tools/test-proxy/ci.yml
Labels: Test-Proxy

#5291 [test proxy] Move migration script to eng/common
  eng/common/testproxy/transition-scripts/README.md
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
  tools/test-proxy/scripts/transition-scripts/README.md
Labels: auto-merge

#5304 [Test-Proxy] During recording, re-use existing request body
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/CompressionTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Labels: Test-Proxy

#5313 Handle multi-line string concatenation with Write-Warning
  eng/common/TestResources/New-TestResources.ps1
Labels: auto-merge, Central-EngSys

#5309 [stress testing] Enable nodepool update via bicep and update node SKUs
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/cluster/README.md
  tools/stress-cluster/cluster/azure/cluster/acr.bicep
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
  tools/stress-cluster/cluster/azure/main.bicep
  tools/stress-cluster/cluster/azure/monitoring/stress-status-workbook.bicep
  tools/stress-cluster/cluster/azure/monitoring/stress-test-workbook.bicep
  tools/stress-cluster/cluster/azure/parameters/dev.json
  tools/stress-cluster/cluster/azure/parameters/pg.json
  tools/stress-cluster/cluster/azure/parameters/prod.json
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
  tools/stress-cluster/cluster/provision.ps1
Labels: auto-merge, Central-EngSys

#5318 Proxy Version Update
  eng/common/testproxy/target_version.txt
Labels: auto-merge

#5308 Fix suffix `*` handling in our `CODEOWNERS` path matcher
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeownersFileTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/Azure.Sdk.Tools.RetrieveCodeOwners.Tests.csproj
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ProgramGlobPathTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/baz/cor/c.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/baz_.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/qux/abc/d.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/glob_path_CODEOWNERS
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
Labels: Central-EngSys

#5316 Temporarily disable error handling for Get-AzKeyVault -InRemovedState
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: auto-merge, Central-EngSys

#5329 Register preview features in stress cluster
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys

#5325 Improve warning messages on invalid `CODEOWNERS` paths.
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
Labels: Central-EngSys

#5352 Make `PipelineOwnersExtractor` compile again + refactor
  tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Configuration/PostConfigureKeyVaultSettings.cs
  tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Configuration/SecretClientProvider.cs
  tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Processor.cs
  tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Program.cs
  tools/pipeline-owners-extractor/PipelineOwnersExtractor.sln.DotSettings
Labels: Central-EngSys

#5330 Fix regex-based matcher to be a strict subset of GitHub-based `CODEOWNERS` matcher.
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeownersFileTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CodeownersManualAnalysisTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ProgramGlobPathTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/cor.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/cor/gra/a.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/InputDir/cor2/a.txt
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/glob_path_CODEOWNERS
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
Labels: Central-EngSys

#5380 Delete tools/apiview/parsers/swagger-api-parser/global.json
  tools/apiview/parsers/swagger-api-parser/global.json
Labels: Central-EngSys

#5379 Update `.NET` from `6.0.403` to `7.0.102` + `DOTNET_ROLL_FORWARD`: `Major` + fix wrong quotes in `install-net.yml`
  eng/pipelines/templates/steps/install-dotnet.yml
  global.json
Labels: Central-EngSys

#5262 Test-Proxy Transition Report Script
  scripts/python/assets-automation/.gitignore
  scripts/python/assets-automation/README.md
  scripts/python/assets-automation/generate_assets_report.py
  scripts/python/assets-automation/requirements.txt
Labels: Central-EngSys

#5395 Install `.NET 6.0.x` runtime. Remove `DotNetCoreVersion` param. Undo `DOTNET_ROLL_FORWARD`.
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/steps/install-dotnet.yml
Labels: Central-EngSys

#5398 Revert "Install `.NET 7.0.x` from `global.json` and `.NET 6.0.0` runtime. Remove `DotNetCoreVersion` param. (#5395)
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/steps/install-dotnet.yml
Labels: Central-EngSys

#5397 Repair Failing Livetests Again
  eng/pipelines/templates/steps/test-proxy-local-tool.yml
Labels: Central-EngSys, Test-Proxy

#5354 Introduce `DefaultAzureCredentialWithoutManagedIdentity` to `PipelineOwnersExtractor` to work around issue with unexpected managed identity
  tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Program.cs
Labels: Central-EngSys

#5421 Update apiview-review-gen-swagger.yml
  eng/pipelines/apiview-review-gen-swagger.yml
Labels: Central-EngSys

#5328 stress test docker baseimage updates
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  tools/stress-cluster/chaos/examples/network-stress-example/Dockerfile
  tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Dockerfile
Labels: Central-EngSys, Stress

#5366 Bugfix: when looking for a match in `CODEOWNERS`, do not emit error message for commented out paths
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CodeownersManualAnalysisTests.cs
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
Labels: Central-EngSys

#5412 Improve diagnostics for copy-docs-to-blobstorage script
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: auto-merge

#5419 Update `PipelineOwnersExtractorVersion` to `1.0.0-dev.20230211.1` to deploy `PipelineOwnersExtractor` pipeline fix for spurious MSI Azure credential
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys

#5088 Enable the new, regex-based, wildcard-supporting CODEOWNERS matcher
  tools/code-owners-parser/CodeOwnersParser/CodeownersFile.cs
Labels: EngSys, Central-EngSys

#5428 Comment update: clarify we need `sdk` in `install-dotnet.yml` due to `asp.net core` runtime
  eng/pipelines/templates/steps/install-dotnet.yml
Labels: Central-EngSys

#5427 fix(build): cadl build error when repo url does not end with `.git`
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: auto-merge

#5436 Update Approve label
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
Labels: APIView, Central-EngSys

#5437 Use `CodeownersFile.UseRegexMatcherDefault` everywhere where applicable + remove obsolete tests
  eng/common/scripts/get-codeowners.ps1
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ProgramSimplePathTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
  tools/code-owners-parser/CodeOwnersParser/CodeownersFile.cs
Labels: auto-merge, Central-EngSys

#4729 Expanding our http-pipeline sample into a full test project
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineSample.sln
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineSample/Azure.Sdk.Tools.TestProxy.HttpPipelineSample.csproj
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineSample/MyImplementorClass.cs
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineSample/Program.cs
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineSample/README.md
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineSample/TestProxyTransport.cs
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineTestsExample/Azure.Sdk.Tools.TestProxy.HttpPipelineTestsExample.csproj
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineTestsExample/README.md
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineTestsExample/SampleTestBaseClass.cs
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineTestsExample/SampleTestImplementation.cs
  tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineTestsExample/recordings/BasicTest.json
  tools/test-proxy/sample-clients/net/http-pipeline/Program.cs
Labels: Test-Proxy

#5384 `Info/Active/` now offers data for individual sessions
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/InfoTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/Exceptions/SessionNotActiveException.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Info.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/ActiveMetadataModel.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/RunTimeMetadataModel.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/ActiveExtensions.cshtml
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/Error.cshtml
Labels: Test-Proxy

#5453 Add width property to reviewer image in API review page
  src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
Labels: auto-merge

#5456 [Perf] Add parameter TimeoutInMinutes, update pools
  eng/common/pipelines/templates/jobs/perf.yml
  tools/perf-automation/tests.yml
Labels: auto-merge

#5403 Add `test-proxy` contributing.md
  tools/test-proxy/CONTRIBUTING.md
Labels: Central-EngSys

#5452 Update `NotificationConfiguration` package to `20230214.1` to enable `CODEOWNERS` regex matcher everywhere
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys

#5103 Update `get-codeowners.ps1` to work with the updated `RetrieveCodeOwners` executable + add some tests; make assorted refactorings
  .github/CODEOWNERS
  eng/common/scripts/get-codeowners.ps1
  eng/pipelines/agent-pool-migration.yml
Labels: auto-merge, Central-EngSys

#5487 Always use regex matcher when determining contacts for build failure notifications
  tools/notification-configuration/notification-creator/Contacts.cs
Labels: Central-EngSys

#5488 Update `NotificationConfiguration` NuGet package version to `1.0.0-dev.20230216.1` to enable `CODEOWNERS` regex matcher everywhere
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys

#5493 Where applicable, update Windows pools used to `azsdk-pool-mms-win-2022-general` and rename `vmImage` to the `windows-20xx` format
  doc/common/matrix_generator.md
  eng/common-tests/matrix-generator/samples/matrix.json
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/pipelines/agent-pool-migration.yml
  eng/pipelines/apiview-review-gen-swagger.yml
  eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  src/dotnet/APIView/apiview-sync-staging.yml
  src/dotnet/APIView/apiview.yml
  tools/apiview/parsers/cpp-api-parser/ci.yml
Labels: auto-merge, Central-EngSys

#5411 Readme updates to bring clarity around questions that Elendil was asking
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
Labels: Test-Proxy

#5537 [check-spelling] Temporarily pin Node 18 to 18.13.0
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: auto-merge

#5431 Remove the obsolete, prefix-based `CODEOWNERS` matcher
  eng/common/scripts/get-codeowners.ps1
  tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeownersFileTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CodeownersManualAnalysisTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/RetrieveCodeOwnersProgramTests.cs
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/simple_path_CODEOWNERS
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/TestData/test_CODEOWNERS
  tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
  tools/code-owners-parser/CodeOwnersParser/CodeownersFile.cs
  tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs
Labels: Central-EngSys

#5562 Update packages using `tools/code-owners-parser`
  eng/common/scripts/get-codeowners.ps1
  eng/pipelines/templates/variables/globals.yml
Labels: auto-merge, Central-EngSys

#5454 Add Delayed Response
  tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ModifiableRecordSession.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/TransportCustomizations.cs
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Labels: Central-EngSys, Test-Proxy

#5415 Repair python install for `api-stub-generator`
  eng/pipelines/apiview-review-gen-python.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
  packages/python-packages/api-stub-generator/ci.yml
  scripts/python/util/install_python_version.py
  src/dotnet/APIView/apiview.yml
Labels: Central-EngSys

#5568 Adjust Migration Guidance + which files `java` transition run picks up
  eng/common/testproxy/transition-scripts/README.md
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
Labels: auto-merge, Central-EngSys
