Repository Azure/azure-sdk-tools, pull requests merged in 2023-03, with the labels that each got.

#5581 Proxy Version Update
  eng/common/testproxy/target_version.txt
Labels: auto-merge, Asset-Sync

#5540 add parameter to set cadl emitter options
  eng/common/scripts/Cadl-Project-Generate.ps1
Labels: auto-merge

#5591 Add devops-pat and az website stores to secret rotation
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Azure/Azure.Sdk.Tools.SecretRotation.Azure.csproj
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Azure/ISecretProvider.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Azure/SecretProvider.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Azure.Sdk.Tools.SecretRotation.Cli.csproj
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Commands/RotationCommandBase.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Configuration/RotationConfiguration.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Configuration/StoreConfiguration.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Core/RotationPlan.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Core/SecretStore.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Core/SecretValue.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.AzureAppService/Azure.Sdk.Tools.SecretRotation.Stores.AzureAppService.csproj
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.AzureAppService/AzureWebsiteStore.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.AzureDevOps/Azure.Sdk.Tools.SecretRotation.Stores.AzureDevOps.csproj
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.AzureDevOps/ServiceAccountPersonalAccessTokenStore.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.KeyVault/KeyVaultCertificateStore.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.KeyVault/KeyVaultSecretStore.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/CoreTests/RotationConfigurationTests.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.sln
Labels: Central-EngSys

#5600 Update swagger manual review gen pipeline to use a variable for swagg…
  eng/pipelines/apiview-review-gen-swagger.yml
Labels: APIView, Central-EngSys

#5603 Logging for api request body for better diagnosability
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: auto-merge, Central-EngSys

#5611 Migrate to using windows-2022 pool
  eng/pipelines/eng-common-sync.yml
Labels: Central-EngSys

#5577 Use --tags and --name for rotation config filtering
  schemas/secret-rotation/1.0.0/schema.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Commands/ListCommand.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Commands/RotateCommand.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Commands/RotationCommandBase.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Program.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Configuration/PlanConfiguration.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Configuration/RotationConfiguration.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Configuration/StoreConfiguration.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/CoreTests/PlanConfigurationTests.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/CoreTests/RotationConfigurationTests.cs
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/Invalid/null.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/Invalid/wrong-schema.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/four.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/named-1.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/named-2.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/one.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/three.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/two.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/Valid/manual-value.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/Valid/random-string.json
  tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.sln
Labels: Central-EngSys

#5595 Use "npm ci" to install cspell and respect package-lock.json
  eng/common/spelling/Invoke-Cspell.ps1
Labels: auto-merge, Central-EngSys

#5620 Delete `/config/`
  .github/CODEOWNERS
  config/1es-pools/azsdk-pool-mms-ubuntu-1604-general/provisioning.json
  config/1es-pools/azsdk-pool-mms-ubuntu-1804-general/provisioning.json
  config/1es-pools/azsdk-pool-mms-ubuntu-2004-general/provisioning.json
  config/1es-pools/azsdk-pool-mms-win-2019-general/provisioning.json
Labels: Central-EngSys

#5624 `/web/pixel-server/` → `/tools/pixel-server/`
  .github/CODEOWNERS
  README.md
  scripts/python/readme_tracking/readme.md
  tools/pixel-server/PixelServer.sln
  tools/pixel-server/PixelServer/Connected Services/Application Insights/ConnectedService.json
  tools/pixel-server/PixelServer/Controllers/TrackingController.cs
  tools/pixel-server/PixelServer/Etc/pixel.png
  tools/pixel-server/PixelServer/PixelServer.csproj
  tools/pixel-server/PixelServer/Program.cs
  tools/pixel-server/PixelServer/Startup.cs
  tools/pixel-server/PixelServer/appsettings.Development.json
  tools/pixel-server/PixelServer/appsettings.json
  tools/pixel-server/README.md
  tools/pixel-server/example.png
  web/pixel-server/PixelServer/Properties/launchSettings.json
Labels: Central-EngSys

#5636 Make `CodeownersEntry.GetHashCode` support Enumerables
  tools/code-owners-parser/CodeOwnersParser/CodeownersEntry.cs
Labels: Central-EngSys

#5633 Move `/scripts/powershell/` to `/eng/scripts/`
  eng/pipelines/setup-tutorial-branch.yml
  eng/pipelines/templates/steps/ref-updater.yml
  eng/scripts/Fix-YamlHeaders.ps1
  eng/scripts/Setup-TutorialBranch.ps1
  eng/scripts/force-push-to-gh-pages.ps1
  eng/scripts/ref-updater.ps1
  eng/scripts/update-docrepo-from-source.ps1
Labels: Central-EngSys

#5617 `/.azure-pipelines/warden.yml` → `/eng/pipelines/doc-warden.yml`
  .github/CODEOWNERS
  eng/pipelines/doc-warden.yml
Labels: Central-EngSys

#5634 Move `/scripts/python/` to `/eng/python/`
  .github/CODEOWNERS
  eng/pipelines/templates/steps/use-python-version.yml
  eng/python/apiview-syncdb/requirements.txt
  eng/python/apiview-syncdb/sync_cosmosdb.py
  eng/python/assets-automation/.gitignore
  eng/python/assets-automation/README.md
  eng/python/assets-automation/generate_assets_report.py
  eng/python/assets-automation/requirements.txt
  eng/python/docs-automation/README.md
  eng/python/docs-automation/example_toc.png
  eng/python/docs-automation/requirements.txt
  eng/python/docs-automation/sync_tocs.py
  eng/python/readme_tracking/readme.md
  eng/python/readme_tracking/update_readmes_for_tracking.py
  eng/python/repo_labels/README.md
  eng/python/util/install_python_version.py
  eng/python/util/reupload_python_packages.py
  src/dotnet/APIView/apiview-sync-staging.yml
Labels: Central-EngSys

#5196 Install packages from cadl package and list installed packages
  eng/pipelines/apiview-review-gen-cadl.yml
  eng/scripts/Create-Apiview-Token-Cadl.ps1
Labels: Central-EngSys

#5515 Handle resource group deprovision race condition
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#5681 Readme for standalone executable + codespaces token conflicts
  tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
  tools/test-proxy/documentation/asset-sync/README.md
Labels: Central-EngSys

#5613 True Version Override in Proxy Tooling
  eng/common/testproxy/override-proxy-version.ps1
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: auto-merge, Test-Proxy

#5702 add healthinsights to Test-SampleMetadata script
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: auto-merge

#5722 Revert "[check-spelling] Temporarily pin Node 18 to 18.13.0 (#5537)"
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: auto-merge

#5752 Update github-event-processor's ci.yml triggers to only include main
  tools/github-event-processor/YmlAndConfigFiles/event-processor.yml
  tools/github-event-processor/YmlAndConfigFiles/scheduled-event-processor.yml
  tools/github-event-processor/ci.yml
Labels: EngSys, GitHub Event Processor

#5762 [Test Proxy] Update recording asset transition script links
  tools/test-proxy/documentation/asset-sync/README.md
Labels: Docs, Test-Proxy

#5742 Add default output to call to `trust-proxy-certificate.ps1`
  eng/common/scripts/trust-proxy-certificate.ps1
Labels: auto-merge

#5794 Explicitly set PSNativeCommandArgumentPassing to Legacy for git push script
  eng/common/scripts/git-branch-push.ps1
Labels: auto-merge

#5816 Update the scheduled event governor based upon the actions rate limit
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/MockGitHubEventClient.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Constants/RateLimitConstants.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/ScheduledEventProcessing.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs
Labels: Central-EngSys, GitHub Event Processor

#5726 [stress] stress test rerun failed jobs feature
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/chaos/examples/network-stress-example/Dockerfile
  tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Dockerfile
Labels: auto-merge, Central-EngSys, Stress

#5830 Tweak to InitialIssueTriage and PullRequestTriage rules
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/MockGitHubEventClient.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/IssueCommentProcessingTests.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/IssueProcessingTests.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/PullRequestCommentProcessingTests.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/PullRequestProcessingTests.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/PullRequestReviewProcessingTests.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Tests.JsonEventPayloads/ManualTriageAfterExternalAssignment_issue_unlabeled_CXP_attention_has_service_attention.json
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Tests.JsonEventPayloads/ManualTriageAfterExternalAssignment_issue_unlabeled_service_attention_has_CXP_attention.json
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueCommentProcessing.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueProcessing.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/PullRequestCommentProcessing.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/PullRequestProcessing.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Utils/CodeOwnerUtils.cs
  tools/github-event-processor/RULES.md
Labels: Central-EngSys, GitHub Event Processor

#5863 Fix issue in email notification when override email is not set
  src/dotnet/APIView/APIViewWeb/Managers/NotificationManager.cs
Labels: Central-EngSys

#5608 Move `get-codeowners.ps1` test mode to `common-tests` + related improvements & cleanup
  eng/common-tests/README.md
  eng/common-tests/ci.yml
  eng/common-tests/get-codeowners/get-codeowners.tests.ps1
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/common/pipelines/templates/steps/run-pester-tests.yml
  eng/common/scripts/get-codeowners.lib.ps1
  eng/common/scripts/get-codeowners.ps1
  tools/code-owners-parser/CodeOwnersParser.sln
  tools/code-owners-parser/ci.yml
Labels: auto-merge, Central-EngSys

#5875 Rename the guidelines checker package
  tools/pylint-extensions/azure-pylint-guidelines-checker/MANIFEST.in
  tools/pylint-extensions/azure-pylint-guidelines-checker/README.md
  tools/pylint-extensions/azure-pylint-guidelines-checker/__init__.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/ci.yml
  tools/pylint-extensions/azure-pylint-guidelines-checker/contribution.md
  tools/pylint-extensions/azure-pylint-guidelines-checker/dev_requirements.txt
  tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/setup.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/__init__.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/__init__.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/api_version_checker_acceptable_class.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/api_version_checker_acceptable_init.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/api_version_checker_violation.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/copyright_header_acceptable.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/copyright_header_violation.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/core_paging_acceptable.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/core_paging_acceptable_and_violation.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/core_paging_violation.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/enum_checker_acceptable.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/enum_checker_violation.py
  tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py
Labels: Central-EngSys

#5877 `/eng/python/` -> `/eng/scripts/python/`
  eng/pipelines/templates/steps/use-python-version.yml
  eng/scripts/python/apiview-syncdb/requirements.txt
  eng/scripts/python/apiview-syncdb/sync_cosmosdb.py
  eng/scripts/python/assets-automation/.gitignore
  eng/scripts/python/assets-automation/README.md
  eng/scripts/python/assets-automation/generate_assets_report.py
  eng/scripts/python/assets-automation/requirements.txt
  eng/scripts/python/docs-automation/README.md
  eng/scripts/python/docs-automation/example_toc.png
  eng/scripts/python/docs-automation/requirements.txt
  eng/scripts/python/docs-automation/sync_tocs.py
  eng/scripts/python/readme_tracking/readme.md
  eng/scripts/python/readme_tracking/update_readmes_for_tracking.py
  eng/scripts/python/repo_labels/README.md
  eng/scripts/python/util/install_python_version.py
  eng/scripts/python/util/reupload_python_packages.py
  src/dotnet/APIView/apiview-sync-staging.yml
Labels: Central-EngSys
