Repository Azure/azure-sdk-tools, pull requests merged in 2024-10, with the labels that each got.

#9074 Update New-TestResources.ps1 to add quotes around shell envvar
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys

#9063 [stress] Sync namespace federated credentials periodically and on startup
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
  tools/stress-cluster/services/Stress.Watcher/Dockerfile
  tools/stress-cluster/services/Stress.Watcher/src/NamespaceEventHandler.cs
  tools/stress-cluster/services/Stress.Watcher/src/Program.cs
Labels: Central-EngSys, Stress

#9093 Run yum update in stress images. Remove account key from bicep
  tools/stress-cluster/cluster/azure/cluster/storage.bicep
  tools/stress-cluster/cluster/azure/main.bicep
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/Dockerfile
  tools/stress-cluster/services/Stress.Watcher/Dockerfile
Labels: Central-EngSys

#9096 Fix container image builds for http fault injector and otel collector
  tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Azure.Sdk.Tools.HttpFaultInjector.csproj
  tools/http-fault-injector/Dockerfile
  tools/stress-cluster/services/otelcollector/Dockerfile
  tools/stress-cluster/services/otelcollector/otel-builder.yml
Labels: Central-EngSys

#9099 Persist oidc env vars in deploy template
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys

#9095 Upgrade revision when revision is requested and if a new parser is re…
  src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
Labels: APIView, Central-EngSys

#9113 Use equality function check for persist oidc token step
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys

#9010 Include optional navigation tree in JSON token schema to support custom navigation panel
  tools/apiview/parsers/apiview-treestyle-parser-schema/CodeFile.json
  tools/apiview/parsers/apiview-treestyle-parser-schema/main.tsp
Labels: APIView, Central-EngSys

#9015 Hide the navigation nodes for unmodified nodes in diff
  src/dotnet/APIView/APIView/Model/CodeFile.cs
  src/dotnet/APIView/ClientSPA/src/app/_models/navigationTreeModels.ts
  src/dotnet/APIView/ClientSPA/src/app/_workers/apitree-builder.worker.ts
Labels: APIView, Central-EngSys

#9171 Upgrade the revisions on the fly
  src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
Labels: APIView, Central-EngSys

#9134 Use $GITHUB_EVENT_PATH variable instead of inline file writing
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: Central-EngSys

#9182 Update JS API parser to 2.0.2
  src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
  src/dotnet/APIView/apiview.yml
Labels: APIView, Central-EngSys

#9202 Set resource group env variable early so remove always works
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys

#9199 Fix missing CloseAddressedIssues in gh event processor
  .github/workflows/scheduled-event-processor.yml
Labels: Central-EngSys

#9185 Resolve bug in file upload
  src/dotnet/APIView/APIViewWeb/Helpers/HelperAttributes.cs
  src/dotnet/APIView/APIViewWeb/Languages/JsonLanguageService.cs
  src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.ts
Labels: APIView, Central-EngSys

#9211 Update APIView token TypeSpec to generate valid JSON schema with top…
  tools/apiview/parsers/apiview-treestyle-parser-schema/CodeFile.json
  tools/apiview/parsers/apiview-treestyle-parser-schema/main.tsp
  tools/apiview/parsers/apiview-treestyle-parser-schema/package-lock.json
  tools/apiview/parsers/apiview-treestyle-parser-schema/package.json
  tools/apiview/parsers/apiview-treestyle-parser-schema/tspconfig.yaml
Labels: APIView, Central-EngSys

#9212 Handle cleanup for leased and encrypted storage accounts. Reduce throttling
  eng/common/scripts/Helpers/Resource-Helpers.ps1
  eng/pipelines/live-test-cleanup-template.yml
  eng/pipelines/live-test-cleanup.yml
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#8454 prettify java-packages/codesnippet-maven-plugin readme java snippets
  packages/java-packages/codesnippet-maven-plugin/README.md
Labels: no-recent-activity

#9225 Disable auto-baseline on non default branch
  eng/pipelines/templates/stages/1es-redirect.yml
Labels: Central-EngSys

#9235 Support branch name with special char in create review step
  eng/common/pipelines/templates/steps/create-apireview.yml
Labels: Central-EngSys

#9236 Refactor PackageProps to make the Yaml loading and processing methods common
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys

#9230 Update apiview token prefix
  src/dotnet/APIView/APIView/Model/V2/ReviewLine.cs
  src/dotnet/APIView/APIView/Model/V2/ReviewToken.cs
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/azure.data.tables.12.9.0.json
  src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
  tools/apiview/parsers/apiview-treestyle-parser-schema/CodeFile.json
  tools/apiview/parsers/apiview-treestyle-parser-schema/main.tsp
Labels: APIView, Central-EngSys

#9257 Update JS parser version
  src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
  src/dotnet/APIView/apiview.yml
Labels: APIView, Central-EngSys

#9249 [stress testing] Allow default matrix selection override
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/chaos/README.md
Labels: Central-EngSys

#9270 ADD readme for APIViewJSON Utility
  src/dotnet/APIView/APIViewJsonUtility/README.md
Labels: APIView, Central-EngSys

#9276 [stress testing] Set up storage file data contributor role for cluster test identities
  tools/stress-cluster/cluster/azure/cluster/workloadapproles.bicep
Labels: Central-EngSys

#9292 Reduce unnecessary delete calls to ARM for storage accounts
  eng/common/scripts/Helpers/Resource-Helpers.ps1
  eng/pipelines/live-test-cleanup-template.yml
Labels: Central-EngSys
