Repository Azure/azure-sdk-tools, pull requests merged in 2024-11, with the labels that each got.

#9299 Update build tags before exporting to kusto
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/AzurePipelines/AzurePipelinesProcessor.cs
  tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/AzurePipelines/BuildCompleteQueueWorker.cs
Labels: Central-EngSys

#9333 Live test cleanup - sub deployments, immutable containers, purge skip
  eng/common/scripts/Helpers/Resource-Helpers.ps1
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#9331 Finish docs cleanup
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: Docs

#9353 Enable subscription scoped deployment cleanup
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#9364 Fix missing stress matrix display name filter
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: Central-EngSys

#9386 Fix RG removal comment in cleanup
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#9396 Fix issues in diff when end of context line has diff
  src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
  src/dotnet/APIView/APIViewWeb/LeanModels/CodePanelModels.cs
Labels: APIView, Central-EngSys

#9405 Fix bug skipping removal of worm storage resource groups
  eng/scripts/live-test-resource-cleanup.ps1
Labels: Central-EngSys

#9326 Bump powershell yaml versions to 0.4.7
  eng/common-tests/psmodule-helpers/Install-Module-Parallel.ps1
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/TypeSpec-Project-Generate.ps1
  eng/common/scripts/TypeSpec-Project-Process.ps1
  eng/common/scripts/TypeSpec-Project-Sync.ps1
  eng/common/scripts/Update-DocsMsToc.ps1
  eng/common/scripts/Verify-Resource-Ref.ps1
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys

#9392 Support override of powershell module feeds
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: Central-EngSys

#9428 Remove previous cadl scripts
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: Automation Tool
