Repository Azure/azure-sdk-tools, pull requests merged in 2024-06, with the labels that each got.

#8369 Remove PATVAR from PipelineGenerator
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/CommandParserOptions/DefaultOptions.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/PipelineGenerationContext.cs
  tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
Labels: Pipeline Generator

#8370 PAT Removal from pipeline generation yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/pipelines/pipeline-generation-single.yml
  eng/pipelines/pipeline-generation.yml
Labels: Pipeline Generator

#8377 Plumb env vars through deploy test resources
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
Labels: Central-EngSys

#8373 Use DOTNET_ROLL_FORWARD: 'Major' for test-proxy
  eng/common/testproxy/test-proxy-tool.yml
Labels: Central-EngSys

#8411 Update github-event-processor's Octokit version to 12.0.0
  tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Azure.Sdk.Tools.GitHubEventProcessor.csproj
Labels: GitHub Event Processor

#8412 Update github-event-processor to 1.0.0-dev.20240610.2
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: GitHub Event Processor

#8410 Update language param name to avoid collision with common eng variable
  eng/pipelines/devops-create-package-workitem.yml
  eng/scripts/Create-Package-WorkItem.ps1
Labels: Engagement Experience

#8440 Add Azure/azure-rest-api-specs to the list of repositories to sync common labels
  tools/github/data/repositories.txt
Labels: CODEOWNERS Linter

#8450 Fix missing owners for path error to include path
  tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter.Tests/Verification/OwnersTests.cs
  tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Constants/ErrorMessageConstants.cs
  tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Verification/CodeownersLinter.cs
  tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Verification/Owners.cs
Labels: CODEOWNERS Linter

#8452 Pass pipeline vnet to live test arm templates
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys

#8422 Merge subscription configuration file values with the supplied subscription config
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/build-test-resource-config.yml
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
  eng/common/TestResources/sub-config/AzurePublicMsft.json
Labels: Central-EngSys

#8483 Add storage blob data owner to stress workload app role list
  tools/stress-cluster/cluster/azure/cluster/workloadapproles.bicep
Labels: Central-EngSys

#8506 [Validate-AzsdkCodeOwners] UX enhancements
  tools/github/scripts/Validate-AzsdkCodeOwner.ps1
Labels: GitHub Issues
