Repository Azure/azure-sdk-tools, pull requests merged in 2024-04, with the labels that each got.

#7975 Pass Group in request to get package status
  eng/common/scripts/Validate-Package.ps1
Labels: Central-EngSys

#7988 Pass valid original artifact file name in request to APIView
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys

#7989 Remove soft errors in validation step from Devops pipeline
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys

#8015 Use different service connection and az CLI for ACR auth
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Labels: Central-EngSys

#7955 Support for client core libraries
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/models/AnnotationRendererModel.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/models/AnnotationRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/MiscUtils.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/azure/AzureCoreBuilderTraitsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/azure/AzureCoreFluentSetterReturnTypeDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/azure/MavenPackageAndDescriptionDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/azure/ServiceVersionDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/clientcore/ClientCoreBuilderTraitsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/clientcore/ClientCoreFluentSetterReturnTypeDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/clientcore/ExpandableEnumDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/BadAnnotationDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/ConsiderFinalClassDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/IllegalMethodNamesDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/IllegalPackageAPIExportsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/ImportsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/MissingAnnotationsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/MissingJavaDocDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/MissingJavadocCodeSnippetsRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/ModuleInfoDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/NoLocalesInJavadocUrlDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/NoPublicFieldsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/PackageNameDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/UpperCaseEnumValuesDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/UpperCaseNamingDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/utils/BuilderTraitsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/utils/FluentSetterReturnTypeDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/utils/MiscUtils.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/ApiViewProperties.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/Flavor.java
  src/java/apiview-java-processor/src/test/java/com/azure/tools/apiview/processor/diagnostics/rules/azure/MavenPackageAndDescriptionDiagnosticRuleTests.java
  src/java/apiview-java-processor/src/test/java/com/azure/tools/apiview/processor/diagnostics/rules/general/NoLocalesInJavadocUrlDiagnosticRuleTests.java
Labels: APIView

#8053 Pass flag to suppress errors correctly when verifying release change log
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Validate-Package.ps1
Labels: Central-EngSys

#8019 Add retry on error for sparse checkout
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys

#8086 Authenticate requests from APIView to DevOps using managed Identity
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
  src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
Labels: APIView, Central-EngSys

#8110 Show review link in logs and set DevOps project name in request
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: Central-EngSys

#8112 Add polly retry to get artifact URL from DevOps
  src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
Labels: APIView, Central-EngSys

#8115 Introducing a test framework for Java APIView processor
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
  src/java/apiview-java-processor/src/test/java/com/azure/tools/apiview/TestExpectedOutputs.java
Labels: APIView

#8117 Handle the failures when package work item is unassigned
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys

#8128 Fix tsp client publish glob/artifact pathing
  tools/tsp-client/ci.yml
Labels: Central-EngSys

#8131 Update to azure/login@v2
  .github/workflows/event-processor.yml
Labels: Central-EngSys, GitHub Event Processor

#8152 Only make one call to GetPackageInfoJson
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: Docs
