Repository Azure/azure-sdk-tools, pull requests merged in 2024-01, with the labels that each got.

#7485 Update PostConfigureKeyVaultSettings.cs with suggestion s360
  tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Configuration/PostConfigureKeyVaultSettings.cs
Labels: Central-EngSys

#7445 Add package filter parameter for release
  eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
  eng/common/scripts/create-tags-and-git-release.ps1
Labels: Central-EngSys

#7524 apiviewgo skips nested modules
  src/go/cmd/api_view_test.go
  src/go/cmd/module.go
  src/go/cmd/testdata/test_multi_module/A/B/go.mod
  src/go/cmd/testdata/test_multi_module/A/B/test.go
  src/go/cmd/testdata/test_multi_module/A/go.mod
  src/go/cmd/testdata/test_multi_module/A/test.go
  src/go/cmd/testdata/test_multi_module/go.mod
  src/go/cmd/testdata/test_multi_module/test.go
Labels: APIView, Go

#7530 [CODEOWNERS] Remove automation section
  .github/CODEOWNERS
Labels: EngSys, Client

#7532 Apply optional changes to mirrored image
  eng/pipelines/mirror-container-images.yml
  eng/scripts/mirror-container-image.ps1
Labels: Central-EngSys

#7536 Filter packages at verify step
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/create-tags-and-git-release.ps1
Labels: Central-EngSys

#7535 Always pull chaos images
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/values.yaml
Labels: Central-EngSys, Stress

#7533 Use apk update for chaos mesh image
  eng/pipelines/mirror-container-images.yml
Labels: Central-EngSys, Stress

#7543 Add git commit details to stress environment
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.lock
  tools/stress-cluster/chaos/examples/parallel-pod-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_container_env.tpl
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
Labels: Central-EngSys, Stress

#7604 Add Azure/azure-sdk-for-rust to scripts
  tools/github/data/repositories.txt
  tools/github/scripts/Add-AzsdkMilestones.ps1
  tools/github/scripts/Add-AzsdkProjectIssues.ps1
  tools/github/scripts/Snapshot-AzsdkLabels.ps1
  tools/github/scripts/Sync-AzsdkLabels.ps1
Labels: Rust
