Repository Azure/azure-sdk-tools, pull requests merged in 2025-07, with the labels that each got.

#11165 Allow authless pipeline analysis for github coding agent and other flows
  .github/copilot-instructions.md
  .github/workflows/copilot-setup-steps.yml
  eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
  eng/pipelines/templates/steps/upload-llm-artifacts.yml
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Analyzer/EnforceToolsExceptionHandling.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/CliIntegrationTests.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/MockServices/MockDevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.sln
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/SharedOptions.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Configuration/Constants.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/LogAnalysisHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TestHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TokenUsageHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/AnalyzePipelineResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/FailedTestRunResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/LogAnalysisResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/ObjectCommandResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/PackageResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/OutputService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/AnalyzePipelineTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/PipelineAnalysisTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/PipelineDetailsTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/PipelineTestsTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/Test/TestAnalysisTool.cs
  tools/azsdk-cli/CONTRIBUTING.md
Labels: Central-EngSys, azsdk-cli

#11228 [azsdk-cli] Use chained token credential. Handle pipeline links for analysis.
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/SharedOptions.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/LogAnalysisHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/UserHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AzureService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/PipelineAnalysisTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/PipelineDetailsTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/PipelineTestsTool.cs
Labels: Central-EngSys

#11254 Fallback to interactive credentials when chained token cred fail
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
Labels: DevEx Agent

#11232 [azsdk-cli] Throw exception if user is not authorized with devops REST calls
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/PipelineAnalysisTool.cs
Labels: Central-EngSys

#11329 Fix release stage conditional for azsdk cli
  tools/azsdk-cli/ci.yml
Labels: Central-EngSys

#11353 [azsdk-cli] Fixes for mac install
  eng/common/mcp/azure-sdk-mcp.ps1
  eng/common/scripts/Helpers/AzSdkTool-Helpers.ps1
Labels: Central-EngSys
