Repository Azure/azure-sdk-tools, pull requests merged in 2025-03, with the labels that each got.

#9951 Update pinned python API parser version to 0.3.15
  eng/pipelines/apiview-review-gen-python.yml
Labels: APIView, Central-EngSys

#9953 Update API revision metadata when processing update requests from sandboxing pipeline
  src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
Labels: APIView, Central-EngSys

#9954 Python API review is not generated using correct package name
  packages/python-packages/apiview-stub-generator/CHANGELOG.md
  packages/python-packages/apiview-stub-generator/apistub/_stub_generator.py
  packages/python-packages/apiview-stub-generator/apistub/_version.py
  packages/python-packages/apiview-stub-generator/tests/apiview_test.py
Labels: Central-EngSys

#9952 Update pinned python API parser version to 0.3.16
  eng/pipelines/apiview-review-gen-python.yml
  src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Labels: APIView, Central-EngSys

#9955 Update original file path value in detect change request to APIView
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: APIView, Central-EngSys

#9939 Enable auto-updates for stress images
  eng/containers/ci.yml
  tools/http-fault-injector/Dockerfile
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
Labels: Central-EngSys

#9983 Update stress provision references to new chart location
  tools/stress-cluster/chaos/README.md
  tools/stress-cluster/cluster/README.md
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/file-plugin/README.md
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys

#9943 Use subscription name to assign supportsSafeSecretStandard
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys

#9997 Update java parser version
  src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
  src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
  src/java/apiview-java-processor/pom.xml
Labels: APIView, Central-EngSys

#9998 Fix issue in APIView prod to staging sync
  eng/scripts/python/apiview-syncdb/sync_cosmosdb.py
Labels: APIView, Central-EngSys

#10041 Fix group prefix conditional in test resource removal
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: Central-EngSys

#10051 Update JS API parser version
  src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
  src/dotnet/APIView/apiview.yml
Labels: Central-EngSys

#10053 Add ACR image pruning to scheduled docker publish pipeline
  eng/containers/ci.yml
  eng/pipelines/prune-acr-images.yml
  eng/pipelines/publish-docker-image-isolated.yml
  eng/pipelines/publish-docker-image.yml
  eng/scripts/prune-acr-images.ps1
Labels: Central-EngSys

#10000 [APIView] Mark apiview pipeline as release pipeline
  src/dotnet/APIView/apiview.yml
Labels: APIView, Central-EngSys

#10096 Package Properties processing updates
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys

#10099 Add option to create self contained test resources post script
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys

#10135 Import Az powershell module in self contained post script task
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys

#10158 [CODEOWNERS] Add Squire to stuff
  .github/CODEOWNERS
Labels: EngSys, Client
