Repository Azure/azure-sdk-tools, pull requests merged in 2025-01, with the labels that each got.

#9456 Accesibility/linefeatures
  src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
  src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.spec.ts
  src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
  src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
  src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
  src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
  src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
  src/dotnet/APIView/ClientSPA/src/app/_helpers/common-helpers.ts
  src/dotnet/APIView/ClientSPA/src/ng-prime-overrides.scss
Labels: APIView, Central-EngSys

#9611 Convert Typespec API reviews
  src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
  src/dotnet/APIView/APIViewUnitTests/CodeFileTests.cs
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/Azure.Template.cpp.json
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/Azure.Template.cpp_new.json
  src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/TypeSpecLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
Labels: Central-EngSys

#9529 Use -Mail for test resources local user lookup to support TME
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys

#9650 Remove sovereign cloud testing support
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/pipelines/live-test-cleanup.yml
Labels: Central-EngSys

#9676 Do not show the line as modified if all tokens in a line is skipped
  src/dotnet/APIView/APIView/Model/V2/ReviewLine.cs
  src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
  src/dotnet/APIView/APIViewUnitTests/CodeFileTests.cs
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/app-conf-change-in-skipped-diff.json
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/app-conf.json
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/app-conf_without_skip_diff.json
  src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
Labels: Central-EngSys

#9680 Update dotnet parser to skip RequiresUnreferencedCode attribute
  tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/TreeToken/CodeFileBuilder.cs
  tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CSharpAPIParserTests.csproj
  tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CodeFileTests.cs
Labels: APIView, Central-EngSys

#9681 Sparse checkout 1espt auto-baselining file by default
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys

#9687 Migrate stress storage cluster to TME
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.lock
  tools/stress-cluster/chaos/examples/parallel-pod-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/cluster/azure/cluster/acr.bicep
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
  tools/stress-cluster/cluster/azure/main.bicep
  tools/stress-cluster/cluster/azure/parameters/storage.json
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys

#9715 Introduce a root folder to save the logs and artifacts
  tools/spec-gen-sdk/CHANGELOG.md
  tools/spec-gen-sdk/package.json
  tools/spec-gen-sdk/src/automation/entrypoint.ts
  tools/spec-gen-sdk/src/automation/workflowPackage.ts
Labels: Central-EngSys

#9700 Add fallback user id lookup for test resource deployment
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys

#9695 Enable conversion of existing Swift reviews and disable conversion of…
  src/dotnet/APIView/APIViewWeb/Languages/SwiftLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/TypeSpecLanguageService.cs
Labels: APIView, Central-EngSys

#9731 Connect to APIView app config using managed identity
  src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
  src/dotnet/APIView/APIViewWeb/Program.cs
Labels: APIView, Central-EngSys

#9724 Adopted 1es common template
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
  eng/common/pipelines/templates/stages/archetype-spec-gen-sdk.yml
Labels: Central-EngSys, Automation Tool

#9143 Publish JS parser using system identity
  tools/apiview/parsers/js-api-parser/ci.yml
Labels: APIView, Central-EngSys

#9741 Update .NET parser version installed to APIView
  src/dotnet/APIView/apiview.yml
Labels: APIView, Central-EngSys
