Repository Azure/azure-sdk-tools, pull requests merged in 2025-02, with the labels that each got.

#9747 Pass non sparse parameters through to PR job matrix generator
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: Central-EngSys

#9745 Pass arm template parameter for TME context
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys

#9774 Stress release pipeline - deploy to TME storage cluster
  eng/pipelines/templates/jobs/stress-test-release.yml
Labels: Central-EngSys

#9781 Flip supportsSafeSecretStandard boolean condition
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys

#9788 Add AdditionalMatrixConfigs the CIMatrixConfigs
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys

#9821 Fix the expression used for AddDevVersion param in save package properties
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: Central-EngSys

#9766 Update parser version in Cosmos when converting code file to tree model
  src/dotnet/APIView/APIViewWeb/Languages/CLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/JsonLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
  src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
  src/dotnet/APIView/APIViewWeb/Languages/SwiftLanguageService.cs
  src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
  src/dotnet/APIView/APIViewWeb/Models/APICodeFileModel.cs
Labels: APIView, Central-EngSys

#9832 Fix the issue in adding dev version in package info
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: Central-EngSys

#9820 [APIView] Disable auto upgrade of APIView review
  src/dotnet/APIView/APIViewUnitTests/APIRevisionsManagerTests.cs
  src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
Labels: APIView, Central-EngSys

#9896 Remove trailing slash addition to ExcludePaths
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys

#9888 Move stress helm charts to azuresdkartifacts. Add publish pipeline. Migrate to TME
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  eng/pipelines/templates/jobs/stress-cluster-provision.yml
  eng/pipelines/templates/jobs/stress-test-release.yml
  tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-example/templates/network_loss.yaml
  tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.lock
  tools/stress-cluster/chaos/examples/network-stress-scenarios-example/templates/network_loss.yaml
  tools/stress-cluster/chaos/examples/parallel-pod-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
  tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
  tools/stress-cluster/cluster/README.md
  tools/stress-cluster/cluster/azure/cluster/cluster.bicep
  tools/stress-cluster/cluster/azure/parameters/pg.json
  tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/publish.yml
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/update-charts.ps1
  tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
  tools/stress-cluster/cluster/provision.ps1
Labels: Central-EngSys

#9928 Include skipped diff and empty lines from active revision when diffing
  src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
  src/dotnet/APIView/APIViewUnitTests/CodeFileTests.cs
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/azure-schemaregistry_python.json
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/azure-schemaregistry_python_diff.json
  src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
Labels: APIView, Central-EngSys

#9917 Add condition parameter to detect-api-changes template
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: Central-EngSys

#9936 Fix apiview group issue
  src/dotnet/APIView/APIView/Model/V2/ReviewLine.cs
  src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
  src/dotnet/APIView/APIViewUnitTests/CodeFileTests.cs
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/Azure.Template.cpp_new.json
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/azure-schemaregistry_python-with-overload_relatedto-NEW.json
  src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/azure-schemaregistry_python-with-overload_relatedto-OLD.json
  src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
Labels: APIView, Central-EngSys
