Repository Azure/azure-sdk-tools, pull requests merged in 2025-06, with the labels that each got.

#10681 Specify run directory as repo root for mcp runner
  eng/common/mcp/azure-sdk-mcp.ps1
Labels: Central-EngSys, azsdk-cli

#10694 Use correct leading slash in common.ps1 repo root resolution
  eng/common/scripts/common.ps1
Labels: Central-EngSys

#10813 New MCP tools to link namespace approval issue and to add SDK info to…
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Azure.Sdk.Tools.Cli.csproj
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/UserHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/ReleasePlan.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SDKWorkFlowTool/SDKWorkFlowTool.cs
Labels: Central-EngSys, Engagement Experience

#10887 [CODEOWNERS] Add .NET team to tools paths
  .github/CODEOWNERS
Labels: EngSys, Client

#10914 Release readiness mcp tool
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/SharedOptions.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/PackageResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleaseReadiness/ReleaseReadinessTool.cs
Labels: Engagement Experience

#10987 Fix path in mcp installer
  eng/common/mcp/azure-sdk-mcp.ps1
Labels: Central-EngSys

#11016 Update response to include work item
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
Labels: Engagement Experience
