Repository Azure/azure-sdk-tools, pull requests merged in 2025-05, with the labels that each got.

#10475 Added changes to fetch API review links and other code restructing to…
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Helpers/GitHelper.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Helpers/SpecPullRequestHelper.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Helpers/TypeSpecHelper.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/ApiviewData.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/GenericResponse.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/PullRequestDetails.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/ReleasePlan.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/TypeSpecProject.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Program.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Services/DevOpsService.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Services/GitHubService.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/ReleasePlanTool.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SDKWorkFlowTool.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SpecCommonTools.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SpecPullRequestTool.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SpecPullRequestTools.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SpecValidationTool.cs
  tools/mcp/dotnet/AzureSDKSpecToolTests/ReleasePlanTest.cs
  tools/mcp/dotnet/AzureSDKSpecToolTests/SpecPullRequestTest.cs
Labels: Central-EngSys, Engagement Experience

#10572 Add azure pipelines tool and AI agent vector search
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/Azure.Sdk.Tools.Cli.Contract.csproj
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Azure.Sdk.Tools.Cli.Tests.csproj
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/CliIntegrationTests.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Azure.Sdk.Tools.Cli.csproj
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AIAgentService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelinesTool/AzurePipelinesTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HostServer/HostServerTool.cs
Labels: Central-EngSys

#10574 Restructure AI Agent service to connect when service is required
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AIAgentService.cs
Labels: Central-EngSys

#10509 `azsdk-cli` MCP Server
  .editorconfig
  global.json
  tools/azsdk-cli/Azure.SDK.Tools.Cli.sln
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/Azure.Sdk.Tools.Cli.Contract.csproj
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/MCPTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/MCPToolInterface.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/README.md
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Azure.Sdk.Tools.Cli.Tests.csproj
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/CliIntegrationTests.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TestHelpers/TestLogger.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Azure.Sdk.Tools.Cli.csproj
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Azure.Sdk.Tools.Cli.http
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/CommandFactory.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/SharedOptions.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TypeSpecHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/CommandResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/ReleasePlan.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/TypeSpecProject.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Program.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/README.md
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AIAgentService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AzureService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/DevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/GitHubService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelinesTool/AzurePipelinesTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HelloWorldTool/HelloWorldTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HostServer/HostServerTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/README.md
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/appsettings.Development.json
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/appsettings.json
  tools/azsdk-cli/Program.cs
  tools/azsdk-cli/README.md
  tools/azsdk-cli/Tools/HttpClientExt.cs
  tools/azsdk-cli/Tools/WeatherTools.cs
  tools/azsdk-cli/azsdk.csproj
  tools/azsdk-cli/ci.yml
Labels: Central-EngSys

#10587 Produce `azsdk` binary!
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/MCPToolInterface.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Azure.Sdk.Tools.Cli.csproj
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/CommandFactory.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/TypeSpecProject.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HelloWorldTool/HelloWorldTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HostServer/HostServerTool.cs
  tools/azsdk-cli/ci.yml
Labels: azsdk-cli

#10610 Merge AZure SDK TypeSpec MCP to Azure SDK CLI MCP server
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/SpecPullRequestHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TypeSpecHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/ApiviewData.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/CommandResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/GenericResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/PullRequestDetails.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/ReleasePlan.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/TypeSpecProject.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AIAgentService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelinesTool/AzurePipelinesTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HelloWorldTool/HelloWorldTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HostServer/HostServerTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SDKWorkFlowTool/SDKWorkFlowTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecCommonTools/SpecCommonTools.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecPullRequestTools/SpecPullRequestTools.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecValidationTool/SpecValidationTool.cs
Labels: Central-EngSys

#10652 Allow SDK gen for data plane only if api stewardship approval is present
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SDKWorkFlowTool/SDKWorkFlowTool.cs
Labels: Central-EngSys

#10663 Add dynamic output formats. Use factory for dynamic agents based on model opts
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/MCPTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/MCPToolInterface.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/CliIntegrationTests.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Services/OutputServiceTests.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/CommandFactory.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/SharedOptions.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TokenUsageHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/CommandResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/GenericResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/OutputModes.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/DefaultCommandResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/LogAnalysisResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/SDKWorkflowResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Program.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AIAgentService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/Agent/AzureAgentService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/Agent/AzureAgentServiceFactory.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/OutputService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelinesTool/AzurePipelinesTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HelloWorldTool/HelloWorldTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SDKWorkFlowTool/SDKWorkFlowTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecCommonTools/SpecCommonTools.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecPullRequestTools/SpecPullRequestTools.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecValidationTool/SpecValidationTool.cs
Labels: Central-EngSys, azsdk-cli

#10665 Fixes to auto-download/start azsdk mcp
  eng/common/mcp/azure-sdk-mcp.ps1
Labels: Central-EngSys, azsdk-cli

#10679 Performance improvements for Java's ApiView generator
  src/java/apiview-java-processor/pom.xml
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/azure/MavenPackageAndDescriptionDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/ConsiderFinalClassDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/ImportsDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/MissingEqualsAndHashCodeDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/NoLocalesInJavadocUrlDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/general/UpperCaseNamingDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/utils/FluentSetterReturnTypeDiagnosticRule.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/RenderClass.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/ReviewLine.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/ReviewToken.java
  src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/TokenKind.java
Labels: Java

#10708 Delete placeholder folder for MCP tool
  tools/mcp/README.md
  tools/mcp/dotnet/AzureSDKDevToolsMCP/AzureSDKDSpecTools.csproj
  tools/mcp/dotnet/AzureSDKDevToolsMCP/AzureSDKDSpecTools.sln
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Helpers/GitHelper.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Helpers/SpecPullRequestHelper.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Helpers/TypeSpecHelper.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/ApiviewData.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/GenericResponse.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/PullRequestDetails.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/ReleasePlan.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Models/TypeSpecProject.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Program.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/README.md
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Services/DevOpsService.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Services/GitHubService.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/ReleasePlanTool.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SDKWorkFlowTool.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SpecCommonTools.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SpecPullRequestTools.cs
  tools/mcp/dotnet/AzureSDKDevToolsMCP/Tools/SpecValidationTool.cs
  tools/mcp/dotnet/AzureSDKSpecToolTests/AzureSDKSpecToolTests.csproj
  tools/mcp/dotnet/AzureSDKSpecToolTests/ReleasePlanTest.cs
  tools/mcp/dotnet/AzureSDKSpecToolTests/SpecPullRequestTest.cs
Labels: Central-EngSys

#10720 Analyze pipeline end to end. Add debug logging.
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/CommandFactory.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/SharedOptions.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TokenUsageHelper.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/AnalyzePipelineResponse.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Program.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelinesTool/AzurePipelinesTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/appsettings.Development.json
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/appsettings.json
Labels: Central-EngSys, azsdk-cli

#10723 Release plan mcp changes
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/ReleasePlan.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
  tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecValidationTool/SpecValidationTool.cs
Labels: Central-EngSys
